### ISSUE TITLE
08 -- Surf & Paddle, RWD Edition --Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#103]
### Tasks

* [x] **Yak Shaving**
  * Create a new issue with tasks and estimates
  * Create a new branch based on `master` named `08--surf+paddle+rwd`
  * Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
  * **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!**
  * Checkpoint: Committed `full.png` and `small.png`
  * Checkpoint: Annotated full-size header
  * Checkpoint: Annotated small-size header
  * Checkpoint: Annotated full-size article
  * Checkpoint: Annotated small-size article
  * Checkpoint: Annotated full-size footer
  * Checkpoint: Annotated small-size footer
  * Checkpoint: Annotated full-size sidebar
  * Checkpoint: Annotated small-size sidebar
* [x] **Surf & Paddle RWD**
  * Checkpoint: Clean slate
  * Checkpoint: HTML5 Boilerplate
  * Checkpoint: Adding assets for logo
  * Checkpoint: Linked fonts for icons and copy
  * Checkpoint: Small-size header complete!
  * Checkpoint: Small-size footer complete!
  * Checkpoint: Small-size columns complete!
  * Checkpoint: Small-size article complete!
  * Checkpoint: Small-size sidebar complete!
  * Checkpoint: Small-size layout complete!
  * Checkpoint: Small-size header complete!
  * Checkpoint: Full-size footer complete!
  * Checkpoint: Full-size columns complete!
  * Checkpoint: Full-size article complete!
  * Checkpoint: Full-size sidebar complete!
  * Checkpoint: Full-size layout complete!
  * Checkpoint: Medium-size header complete!
  * Checkpoint: Medium-size footer complete!
  * Checkpoint: Medium-size columns complete!
  * Checkpoint: Medium-size article complete!
  * Checkpoint: Medium-size sidebar complete!
  * Checkpoint: Medium-size layout complete!
* [ ] **Build a Blog**
  * Checkpoint: Repository exists!
  * Checkpoint: Hello, blog!
  * Checkpoint: HTML5 Boilerplate again?
  * Checkpoint: Basic MF'g HTML
  * Checkpoint: Basic 2-column layout
  * Checkpoint: Header fully styled!
  * Checkpoint: Footer fully styled!
  * Checkpoint: Look, ma, I'm a blogger!
  * Mission Complete!

**Comment by TaylorFoster90** [comment]
Surf and Paddle PR
https://github.com/TaylorFoster90/TIY-Assignments/tree/feature/08--surf+paddle+rwd

**Comment by TaylorFoster90** [comment]
Blog PR
https://github.com/TaylorFoster90/TaylorFoster90.github.io/pull/1

**Comment by TaylorFoster90** [comment]
Bugs in Surf and Paddle: 
* [ ] Box Nav is 'blinking' when hovered 
* [ ] On mobile, you can click outside of the box navs and still get click the link
* [ ] Sidebar figcaptions move from under the picture when browser get bigger

**Comment by TaylorFoster90** [comment]
Bugs in Blog : 
* [ ] Everything leaks into everything when window is smaller

**Comment by LoganArnett** [comment]
Great job Taylor, make sure to still get those 2 :+1: on those PR's
