### ISSUE TITLE
08 -- Surf + Paddle RWD Edition -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#104]
### Tasks

* [ ] **Yak Shaving**
  * [x] Create a new issue with tasks and estimates
  * [x] Create a new branch based on `master` named `08--surf+paddle+rwd`
  * [ ] Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * [x] Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
  * **BONUS:** Name your PR something _other_ than the commit message?
* [ ] **Skitch!**
  * Checkpoint: Committed `full.png` and `small.png`
  * Checkpoint: Annotated full-size header
  * Checkpoint: Annotated small-size header
  * Checkpoint: Annotated full-size article
  * Checkpoint: Annotated small-size article
  * Checkpoint: Annotated full-size footer
  * Checkpoint: Annotated small-size footer
  * Checkpoint: Annotated full-size sidebar
  * Checkpoint: Annotated small-size sidebar
* [ ] **Surf & Paddle RWD**
  * [x] Checkpoint: Clean slate
  * [x] Checkpoint: HTML5 Boilerplate
  * [x] Checkpoint: Adding assets for logo
  * [x] Checkpoint: Linked fonts for icons and copy
  * [x] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Small-size footer complete!
  * [x] Checkpoint: Small-size columns complete!
  * [x] Checkpoint: Small-size article complete!
  * [x] Checkpoint: Small-size sidebar complete!
  * [x] Checkpoint: Small-size layout complete!
  * [x] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Full-size footer complete!
  * [ ] Checkpoint: Full-size columns complete!
  * [ ] Checkpoint: Full-size article complete!
  * [ ] Checkpoint: Full-size sidebar complete!
  * [ ] Checkpoint: Full-size layout complete!
  * [ ] Checkpoint: Medium-size header complete!
  * [ ] Checkpoint: Medium-size footer complete!
  * [ ] Checkpoint: Medium-size columns complete!
  * [ ] Checkpoint: Medium-size article complete!
  * [ ] Checkpoint: Medium-size sidebar complete!
  * [ ] Checkpoint: Medium-size layout complete!
* [ ] **Build a Blog**
  * [x] Checkpoint: Repository exists!
  * [x] Checkpoint: Hello, blog!
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [x] Checkpoint: Basic MF'g HTML
  * [x] Checkpoint: Basic 2-column layout
  * [x] Checkpoint: Header fully styled!
  * [ ] Checkpoint: Footer fully styled!
  * [ ] Checkpoint: Look, ma, I'm a blogger!
  * [ ] Mission Complete!

**Comment by adamkarb** [comment]
[PR](https://github.com/adamkarb/TIY--Assignments/pull/8)

**Comment by adamkarb** [comment]
Noticed bug: The second p tag inside the article has a different font weight than should be expected.  The first got styled like I suspected but the second retained a bolder look...

**Comment by adamkarb** [comment]
[HTML preview](http://htmlpreview.github.io/?http://adamkarb.github.io/)

**Comment by jrutishauser** [comment]
:+1:

**Comment by adamkarb** [comment]
Bug lists: 
- No footer styling on either website
- No media queries on the surf+pad

**Comment by LoganArnett** [comment]
The sites look great Adam :surfer:

Make sure that you are creating a checklist for those big fixes so you can continue to update yourself on the progress. 

Always look for 2 :+1: on the PR's and drop a link back to this WIP issue in the comments of the PR as well.

**Comment by adamkarb** [comment]
@LoganArnett check it out

**Comment by al-the-x** [comment]
Also...

![image](https://cloud.githubusercontent.com/assets/96015/5831022/9c2a2aae-a0f7-11e4-8187-fe2f28ac0e82.jpg)
