### ISSUE TITLE
08 -- Surf & Paddle, RWD Edition--Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#105]
### Tasks

* [x] **Yak Shaving** (L)
  * Create a new issue with tasks and estimates
  * Create a new branch based on `master` named `08--surf+paddle+rwd`
  * Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
  * **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!** (M)
  * Checkpoint: Committed `full.png` and `small.png`
  * Checkpoint: Annotated full-size header
  * Checkpoint: Annotated small-size header
  * Checkpoint: Annotated full-size article
  * Checkpoint: Annotated small-size article
  * Checkpoint: Annotated full-size footer
  * Checkpoint: Annotated small-size footer
  * Checkpoint: Annotated full-size sidebar
  * Checkpoint: Annotated small-size sidebar
* [ ] **Surf & Paddle RWD** (L)
  * Checkpoint: Clean slate
  * Checkpoint: HTML5 Boilerplate
  * Checkpoint: Adding assets for logo
  * Checkpoint: Linked fonts for icons and copy
  * Checkpoint: Small-size header complete!
  * Checkpoint: Small-size footer complete!
  * Checkpoint: Small-size columns complete!
  * Checkpoint: Small-size article complete!
  * Checkpoint: Small-size sidebar complete!
  * Checkpoint: Small-size layout complete!
  * Checkpoint: Small-size header complete!
  * Checkpoint: Full-size footer complete!
  * Checkpoint: Full-size columns complete!
  * Checkpoint: Full-size article complete!
  * Checkpoint: Full-size sidebar complete!
  * Checkpoint: Full-size layout complete!
  * Checkpoint: Medium-size header complete!
  * Checkpoint: Medium-size footer complete!
  * Checkpoint: Medium-size columns complete!
  * Checkpoint: Medium-size article complete!
  * Checkpoint: Medium-size sidebar complete!
  * Checkpoint: Medium-size layout complete!
* [ ] **Build a Blog** (L)
  * Checkpoint: Repository exists!
  * Checkpoint: Hello, blog!
  * Checkpoint: HTML5 Boilerplate again?
  * Checkpoint: Basic MF'g HTML
  * Checkpoint: Basic 2-column layout
  * Checkpoint: Header fully styled!
  * Checkpoint: Footer fully styled!
  * Checkpoint: Look, ma, I'm a blogger!
  * Mission Complete!

**Comment by jgarcia99** [comment]
###Issues

*[ ] **Medium query needs more work.

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/15

**Comment by jgarcia99** [comment]
jgarcia99.github.io

**Comment by jgarcia99** [comment]
###Bugs S&P
* [ ] Medium Query.
* [ ] Images on mobile too big cant margin left/right not rendering the browser.
* [ ] Footer too big.
* [ ] Getting figcaption to the bottom.

**Comment by jgarcia99** [comment]
## Bugs Blog
* [ ] Not responsive.
* [ ]Text overlapping.
* [ ] No links to social networks.
* [ ] Getting figcaption to the bottom.

**Comment by jrutishauser** [comment]
:+1:

**Comment by johnalxndr** [comment]
:+1:

**Comment by LoganArnett** [comment]
Make sure your committing often and that you're getting 2 :+1: on those PR's
