### ISSUE TITLE
08--surf+paddle+rwd -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#108]
### Tasks

* [x] M **Yak Shaving** :water_buffalo: 
  * [x] Create a new issue with tasks and estimates :hourglass_flowing_sand: 
  * [x] Create a new branch based on `master` named `08--surf+paddle+rwd` :deciduous_tree: 
  * [x] Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/` 
  * [x] Push and open a Pull Request to `master` (maybe try using `hub pull-request`?) 
  * [x] **BONUS:** Name your PR something _other_ than the commit message?
* [x] L **Skitch!** :art: 
  * [x] Checkpoint: Committed `full.png` and `small.png` 
  * [x] Checkpoint: Annotated full-size header 
  * [x] Checkpoint: Annotated small-size header 
  * [x] Checkpoint: Annotated full-size article
  * [x] Checkpoint: Annotated small-size article
  * [x] Checkpoint: Annotated full-size footer
  * [x] Checkpoint: Annotated small-size footer
  * [x] Checkpoint: Annotated full-size sidebar
  * [x] Checkpoint: Annotated small-size sidebar
* [x] XL **Surf & Paddle RWD** :ocean:
  * [x] Checkpoint: Clean slate
  * [x] Checkpoint: HTML5 Boilerplate
  * [x] Checkpoint: Adding assets for logo
  * [x] Checkpoint: Linked fonts for icons and copy
* [x] L Mobile Site :iphone:   
  * [x] Checkpoint: Small-size header complete!
  * [x] Checkpoint: Small-size footer complete!
  * [x] Checkpoint: Small-size columns complete!
  * [x] Checkpoint: Small-size article complete!
  * [x] Checkpoint: Small-size sidebar complete!
  * [x] Checkpoint: Small-size layout complete!
  * [x] Checkpoint: Small-size header complete!
* [x] L Full size site :computer:  
  * [x] Checkpoint: Full-size footer complete!
  * [x] Checkpoint: Full-size columns complete!
  * [x] Checkpoint: Full-size article complete!
  * [x] Checkpoint: Full-size sidebar complete!
  * [x] Checkpoint: Full-size layout complete!
* [x] L Tablet size site :notebook: 
  * [x] Checkpoint: Medium-size header complete!
  * [x] Checkpoint: Medium-size footer complete!
  * [x] Checkpoint: Medium-size columns complete!
  * [x] Checkpoint: Medium-size article complete!
  * [x] Checkpoint: Medium-size sidebar complete!
  * [x] Checkpoint: Medium-size layout complete!
* [ ] XL **Build a Blog** :pencil:
  * [x] Checkpoint: Repository exists! 
  * [x] Checkpoint: Hello, blog! 
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [x] Checkpoint: Basic MF'g HTML
  * [x] Checkpoint: Basic 2-column layout
  * [x] Checkpoint: Header fully styled! 
  * [ ] Checkpoint: Footer fully styled! 
  * [x] Checkpoint: Look, ma, I'm a blogger!
 * [ ] Mission Complete! :checkered_flag:

**Comment by jaredstevick** [comment]
**Surf & Paddle - Responsive Design:**
https://github.com/jaredstevick/TIY-Assignments/pull/12

**Comment by jaredstevick** [comment]
## Fixlist for mobile
* [ ] links in header not clickable
* [ ] share buttons only clickable on icon
* [ ] recent posts not clickable
* [ ]  mf'ing z-index
* [ ] match colors
* [ ] match fonts

**Comment by jaredstevick** [comment]
## Fixlist for tablet
* [ ] center post author with date text
* [ ] make sure everything scales appropriately

**Comment by jaredstevick** [comment]
## Fixlist for desktop
* [ ] make site not look like shit on retina display

**Comment by jaredstevick** [comment]
Link to Blog:
http://jaredstevick.github.io/

**Comment by jaredstevick** [comment]
## Fixlist for Blog
* [ ] chose better header image
* [ ] avatar has a thin border.... maybe it's not #FFFFFF?
* [ ] Make buttons
* [ ] Style text
* [ ] Style links
* [ ] Add content

**Comment by LoganArnett** [comment]
Good job man :surfer:

**Comment by al-the-x** [comment]
Files are in the wrong place... :(
