### ISSUE TITLE
09 -- Hello JavaScript!-- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#115]

**Comment by carolinapowers** [comment]
### Tasks

* **Yak Shaving** (M)
  * [ ] Create a new _WIP Issue_ with tasks _and estimates!_
  * [ ] Create a new branch called `09--hello-javascript`
  * [ ] Create and commit a new file in `docs/` called `JS.md`
  * [ ] Push the branch to Github and open a PR
  * [ ] Name the PR _descriptively_...
* **Reading JavaScript** (L)
  * [ ] Checkpoint: Created and committed `JS.md`!
  * [ ] Checkpoint: First Literal Documented!
  * [ ] Checkpoint: All Literals Documented!
  * [ ] Checkpoint: To Infinity and beyond!
  * [ ] Checkpoint: First Operator
  * [ ] Checkpoint: Five Operators
  * [ ] Checkpoint: All Ten Operators!
  * [ ] Mission Complete!
* **What's In A Grid?** (L)
  * [ ] Checkpoint: Reset to Boilerplate!
  * [ ] Checkpoint: Basic HTML structure!
  * [ ] Checkpoint: Look at all the colors...
  * [ ] Checkpoint: Looks great in any viewport!
  * [ ] Mission Complete!

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/9

**Comment by LoganArnett** [comment]
Looks good :white_check_mark:
