### ISSUE TITLE
09 -- Hello JavaScript! --  Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#116]
## Deliverables

* A _WIP Issue_ named `09 -- Hello JavaScript!` with tasks and estimates
* A branch in `TIY-Assignments` named `feature/09--hello-javascript` with:
  * a _new_ file in `docs/` called `JS.md` with documentation matching **Requirements**
  * a commit resetting `pub/` to base HTML5 Boilerplate
  * an implementation in `pub/index.html` of:
    * a 8x8 grid of perfect squares
    * alternating dark and light colors in each square
    * distinct border between cells
    * rows labeled "8" to "1"
    * columns labeled "a" to "h"
    * cell "d8" as dark
* A PR in `TIY-Assignments` from `feature/09--hello-javascript` to `master` with:
  * a link to your _WIP Issue_
  * 2x peer review
* Links in your _WIP Issue_ to:
  * your PR in `TIY-Assignments`

## Requirements

**Note:** You _must_ provide the full set of **Deliverables** to avoid **Incomplete** on this assignment.

### Tasks

* **Yak Shaving** (L)
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript** (L)
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [x] Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* **What's In A Grid?** (L)
  * [x] Checkpoint: Reset to Boilerplate!
  * [ ] Checkpoint: Basic HTML structure!
  * [ ] Checkpoint: Look at all the colors...
  * [ ] Checkpoint: Looks great in any viewport!
  * [ ] Mission Complete!

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/16

**Comment by sak55** [comment]
on your way :+1:

**Comment by LoganArnett** [comment]
Take a look at the JS.md file for some syntax issues, after that you're good to go
