### ISSUE TITLE
09 -- Hello JavaScript! -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#117]
### Tasks

* **Yak Shaving** (S)
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript** (XL)
  * [x] Checkpoint: Created and committed `JS.md`! (S)
  * [x] Checkpoint: First Literal Documented! (S)
  * [x] Checkpoint: All Literals Documented! (M)
  * [x] Checkpoint: To Infinity and beyond! (M)
  * [x] Checkpoint: First Operator (S)
  * [x] Checkpoint: Five Operators (M)
  * [x] Checkpoint: All Ten Operators! (L)
  * [x] Mission Complete! (XL)
* **What's In A Grid?** (L)
  * [x] Checkpoint: Reset to Boilerplate! (S)
  * [x] Checkpoint: Basic HTML structure! (M)
  * [x] Checkpoint: Look at all the colors... (S)
  * [x] Checkpoint: Looks great in any viewport! (M)
  * [x] Mission Complete! (L)

**Comment by sak55** [comment]
to view my index
http://htmlpreview.github.io/?https://github.com/sak55/TIY-Assignments/blob/feature/09--hello-javascript/index.md

**Comment by sak55** [comment]
###Known Issues
* Cant get the ratios correct when resizing.
* Outside border is not the same width as the rest. I added a 1px border for the container but 1px+1px != 2px like the other box borders.
* container is above whole grid and not around it.

**Comment by sak55** [comment]
my PR https://github.com/sak55/TIY-Assignments/issues/14

**Comment by LoganArnett** [comment]
Looks good Sam, take a look at your JS.md file real quick to make sure there are no syntax issues
