### ISSUE TITLE
09 -- Hello Javascript! -- Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#119]
### Tasks

* **Yak Shaving**
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript**
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [x] Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* **What's In A Grid?**
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by TaylorFoster90** [comment]
PR
https://github.com/TaylorFoster90/TIY-Assignments/pull/8

**Comment by LoganArnett** [comment]
Looks good Taylor, make sure to continue to use the estimates on each task and to get that second :+1: on the PR
