### ISSUE TITLE
09 -- Hello JavaScript! -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#121]
### Tasks

* **Yak Shaving** --S
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript** --S
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [x] Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* **What's In A Grid?** --M
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/13

**Comment by LoganArnett** [comment]
Looks good RUTISHAUSER!!! Just make sure that you are committing often, even if its just committing after each one of those definitions to get in the habit. Commit early and often :floppy_disk:

**Comment by al-the-x** [comment]
* Should be `pub/css/main.css` and `pub/index.html`
* Needs more commits.
