### ISSUE TITLE
09 -- Hello JavaScript! -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#123]
### Tasks

* **L Yak Shaving**
  * [x] M Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] S Create a new branch called `09--hello-javascript`
  * [x] S Create and commit a new file in `docs/` called `JS.md`
  * [x] S Push the branch to Github and open a PR
  * [x] S Name the PR _descriptively_...
* ** XL Reading JavaScript**
  * [x] S Checkpoint: Created and committed `JS.md`!
  * [x] S Checkpoint: First Literal Documented!
  * [x] M Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] S Checkpoint: First Operator
  * [x] M Checkpoint: Five Operators
  * [x] L Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* ** L What's In A Grid?**
  * [x] S Checkpoint: Reset to Boilerplate!
  * [x] M Checkpoint: Basic HTML structure!
  * [x] M Checkpoint: Look at all the colors...
  * [x] M Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by jaredstevick** [comment]
Link to Pull Request: 
https://github.com/jaredstevick/TIY-Assignments/pull/13

**Comment by LoganArnett** [comment]
Looks good Jared, good work

**Comment by al-the-x** [comment]
Kinda went all over the place with those operators, man. Approach that kind of documentation systematically: top to bottom omitting _nothing_. Even if you just drop flags in the sand -- placeholders -- to give yourself a reminder of what to fill in later, make sure you get full coverage before moving off-topic.
