### ISSUE TITLE
09 -- Hello JavaScript! -- Garrett 

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#124]
* **Yak Shaving** (L)
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript** (XL)
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [ ] Checkpoint: All Literals Documented!
  * [ ] Checkpoint: To Infinity and beyond!
  * [ ] Checkpoint: First Operator
  * [ ] Checkpoint: Five Operators
  * [ ] Checkpoint: All Ten Operators!
  * [ ] Mission Complete!
* **What's In A Grid?** (L)
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [ ] Checkpoint: Look at all the colors...
  * [ ] Checkpoint: Looks great in any viewport!
  * [ ] Mission Complete!

## Deliverables

* [x] A _WIP Issue_ named `09 -- Hello JavaScript!` with tasks and estimates
* [x] A branch in `TIY-Assignments` named `feature/09--hello-javascript` with:
* [x]  a _new_ file in `docs/` called `JS.md` with documentation matching **Requirements**
* [x]  a commit resetting `pub/` to base HTML5 Boilerplate
* [x]  an implementation in `pub/index.html` of:
* [x]  a 8x8 grid of perfect squares
    * [x] alternating dark and light colors in each square
    * [x] distinct border between cells
    * [x] rows labeled "8" to "1"
    * [x] columns labeled "a" to "h"
    * [x] cell "d8" as dark
* [x] A PR in `TIY-Assignments` from `feature/09--hello-javascript` to `master` with:
* [x] A link to your _WIP Issue_
* [ ] 2x peer review
* [x] Links in your _WIP Issue_ to:
   * [x] your PR in `TIY-Assignments`

**Comment by GarrettGraham** [comment]
###ToDo/ ToFix:

* [ ] Need to style the 8x8 with border and ensure perfect squares
* [ ] Center Grid
* [ ] Larger Boxes

**Comment by LoganArnett** [comment]
Hey Garrett, just looking for the [link back to your PR](https://github.com/GarrettGraham/TIY-Assignments/pull/8) to be commented here and for one more :+1: on that PR and then you're good to go
