### ISSUE TITLE
09 -- Hello Javascript -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#125]
### Tasks

* **Yak Shaving**
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript**
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [ ] Checkpoint: Five Operators
  * [ ] Checkpoint: All Ten Operators!
  * [ ] Mission Complete!
* **What's In A Grid?**
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by adamkarb** [comment]
[PR-JS](https://github.com/adamkarb/TIY--Assignments/pull/9)

**Comment by LoganArnett** [comment]
Looks good Adam, but make sure to place your estimates on those top level tasks and to commit early and often. :white_check_mark:

**Comment by al-the-x** [comment]
* No estimates in your _WIP Issue_
* No operators in your _Reading JS_ assignment
