### ISSUE TITLE
10 -- Math-is-Hard -- GarrettGraham

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#130]
### Tasks

* **Yak Shaving** (L)
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `10--math-hard`
  * [x] Create a new directory called `scripts/`
  * [x] Create and commit a new file in `scripts/` called `main.js`
  * [x] Push the branch to Github and open a PR
* **Reading JavaScript** -- Control Flow (L)
  * [x] Checkpoint: Added `if` with examples
  * [x] Checkpoint: Added `else` with examples
  * [x] Checkpoint: Added `return` with examples
  * [ ] Checkpoint: Five control statements!
  * [ ] Mission Complete: Ten control statements!
* **Math is Hard** (XL)
  * [x] Checkpoint: Created and committed and **RAN** `scripts/main.js`
  * [x] Checkpoint: Houston, we have addition. :rocket:
  * [ ] Checkpoint: We are four by four. :four_leaf_clover:
  * [ ] Checkpoint: Division by zero is... :zero:
  * [ ] Checkpoint: "one" plus "one" is 2
  * [ ] Mission Complete!

## Deliverables

* [x] A _WIP Issue_ named `10 -- Math is Hard` with tasks and estimates
* [x] A branch in `TIY-Assignments` named `feature/10--math-hard` with:
  * [x] a commit that creates:
    * [x] a _new_ directory called `scripts/`
    * [x] a file in `scripts/` called `main.js`
  * [ ] new commits to `docs/JS.md` that:
    * [ ] document 10 control-flow keywords
    * [x] minimally including `if`, `else` and `return`
  * [ ] commits to `pub/index.html` or `pub/css/main.css` that:
    * [ ] add dark and light chess pieces to your grid _via CSS_
    * [ ] provide a hover-state to each square that contains a piece
* [x] A PR in `TIY-Assignments` from `feature/10--math-hard` to `master` with:
  * [x] a link to your _WIP Issue_
  * [ ] 2x peer review
* [x] Links in your _WIP Issue_ to:
  * [x] your PR in `TIY-Assignments`

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/pull/9

**Comment by LoganArnett** [comment]
Make sure to reach out to your peers on those PR's and get as many eyes as possible on your code reviews to get those :+1:
