### ISSUE TITLE
10 -- Math is Hard -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#134]
### Tasks

* **Yak Shaving**
  * [ ] Create a new _WIP Issue_ with tasks _and estimates!_
  * [ ] Create a new branch called `10--math-hard`
  * [ ] Create a new directory called `scripts/`
  * [ ] Create and commit a new file in `scripts/` called `main.js`
  * [ ] Push the branch to Github and open a PR
* **Reading JavaScript** -- Control Flow
  * [ ] Checkpoint: Added `if` with examples
  * [ ] Checkpoint: Added `else` with examples
  * [ ] Checkpoint: Added `return` with examples
  * [ ] Checkpoint: Five control statements!
  * [ ] Mission Complete: Ten control statements!
* **Math is Hard**
  * [ ] Checkpoint: Created and committed and **RAN** `scripts/main.js`
  * [ ] Checkpoint: Houston, we have addition. :rocket:
  * [ ] Checkpoint: We are four by four. :four_leaf_clover:
  * [ ] Checkpoint: Division by zero is... :zero:
  * [ ] Checkpoint: "one" plus "one" is 2
  * [ ] Mission Complete!

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/14

**Comment by LoganArnett** [comment]
good commit messages, definitely keeping track of the progress in each step
