### ISSUE TITLE
10-- Math is hard -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#136]
## Deliverables

* A _WIP Issue_ named `10 -- Math is Hard` with tasks and estimates
* A branch in `TIY-Assignments` named `feature/10--math-hard` with:
  * a commit that creates:
    * a _new_ directory called `scripts/`
    * a file in `scripts/` called `main.js`
  * new commits to `docs/JS.md` that:
    * document 10 control-flow keywords
    * minimally including `if`, `else` and `return`
  * commits to `pub/index.html` or `pub/css/main.css` that:
    * add dark and light chess pieces to your grid _via CSS_
    * provide a hover-state to each square that contains a piece
* A PR in `TIY-Assignments` from `feature/10--math-hard` to `master` with:
  * a link to your _WIP Issue_
  * 2x peer review
* Links in your _WIP Issue_ to:
  * your PR in `TIY-Assignments`

## Requirements

**Note:** You _must_ provide the full set of **Deliverables** to avoid **Incomplete** on this assignment.

### Tasks

* **Yak Shaving** (M)
  * [ ] Create a new _WIP Issue_ with tasks _and estimates!_
  * [ ] Create a new branch called `10--math-hard`
  * [ ] Create a new directory called `scripts/`
  * [ ] Create and commit a new file in `scripts/` called `main.js`
  * [ ] Push the branch to Github and open a PR
* **Reading JavaScript** -- Control Flow (L)
  * [ ] Checkpoint: Added `if` with examples
  * [ ] Checkpoint: Added `else` with examples
  * [ ] Checkpoint: Added `return` with examples
  * [ ] Checkpoint: Five control statements!
  * [ ] Mission Complete: Ten control statements!
* **Math is Hard** (XL)
  * [ ] Checkpoint: Created and committed and **RAN** `scripts/main.js`
  * [ ] Checkpoint: Houston, we have addition. :rocket:
  * [ ] Checkpoint: We are four by four. :four_leaf_clover:
  * [ ] Checkpoint: Division by zero is... :zero:
  * [ ] Checkpoint: "one" plus "one" is 2
  * [ ] Mission Complete!

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/17

**Comment by LoganArnett** [comment]
Make sure you're committing often
