### ISSUE TITLE
10-- Math is hard -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#138]
### Tasks
- *\* L Yak Shaving**
  - [x] S Create a new _WIP Issue_ with tasks _and estimates!_
  - [x] S Create a new branch called `10--math-hard`
  - [x] S Create a new directory called `scripts/`
  - [x] S Create and commit a new file in `scripts/` called `main.js`
  - [x] S Push the branch to Github and open a PR
- *\* XL Reading JavaScript*\* -- Control Flow
  - [x] S Checkpoint: Added `if` with examples
  - [x] S Checkpoint: Added `else` with examples
  - [x] S Checkpoint: Added `return` with examples
  - [x] M Checkpoint: Five control statements!
  - [x] Mission Complete: Ten control statements!
- *\* L Math is Hard**
  - [x] M Checkpoint: Created and committed and **RAN** `scripts/main.js`
  - [x] M Checkpoint: Houston, we have addition. :rocket:
  - [x] M Checkpoint: We are four by four. :four_leaf_clover:
  - [x] M Checkpoint: Division by zero is... :zero:
  - [x] L Checkpoint: "one" plus "one" is 2
  - [x] Mission Complete!

**Comment by jaredstevick** [comment]
Link to latest pull request: 
https://github.com/jaredstevick/TIY-Assignments/pull/14
