### ISSUE TITLE
11 -- Coding Dojo Style -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#142]
### Tasks
- [x] M **Yak Shaving** :water_buffalo: 
  - [x] Merge your last PR if you haven't already! (use the merge button, Luke)
  - [x] Pull your `master` branch locally _after_ you merge!
  - [x] Create a new branch called `feature/11--coding-dojo`
  - [x] Delete and commit `scripts/main.js`
  - [x] Create and commit `scripts/string-calculator.js` and `scripts/check-writing.js`
  - [x] Push your branch and open a PR
- [x] L **Reading JavaScript**
  - [x] Checkpoint: `Array` literals: empty and filled
  - [x] Checkpoint: Other ways to create an `Array`?
  - [x] Checkpoint: What's your `length`...?
  - [x] Checkpoint: First Mutator method!
  - [x] Checkpoint: Five Mutators down!
  - [x] Checkpoint: What, there's only 7?
  - [x] Mission Complete!
- [x] XL **Coding Dojo** -- Time for your katas
  - [x] M Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _my_ repo
  - [x] M Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _another_ repo
  - [x] M Checkpoint: TDD **String Calculator** from `"zero"` to `"ten"`! (HipChat that $#!+)
  - [x] M Checkpoint: TDD **Check Writing** from `1` to `10` in _my_ repo
  - [x] M Checkpoint: TDD **Check Writing** from `1` to `10` in _another_ repo
  -  L **BONUS:** TDD **Check Writing** above `20`...?
- [ ] L **A Nice Game of Chess**
  - [x] M Checkpoint: Retyped the example in `scripts/main.js`
  - [x] M Checkpoint: I can move pieces! Well, one, really.
  - [x] M Checkpoint: Moved _both_ sides at least once!
  - [ ] M Checkpoint: Opening complete!
- [x] L [**JavaScript Koans**](https://github.com/mrdavidlaing/javascript-koans)
  - [x] S Checkpoint: Forked and installed...!
  - [x] M Checkpoint: Ran it and it broke... as intended!
  - [x] M Checkpoint: Got `AboutExpects.js` green!
  - [x] M Checkpoint: Got `AboutArrays.js` green!
  - L **BONUS:** Got `AboutFunctions.js` green! (but I'm really confused)
  - L **BONUS:** Got `AboutObjects.js` green! (wasn't that bad, actually)
- [x] L **BLOG IT!**

**Comment by jaredstevick** [comment]
## Deliverables

* [ ] _WIP Issue_ named `11 -- Coding Dojo Style` with tasks and estimates
* [ ] _WIP Branch_ named `feature/11--coding-dojo` with:
  * [ ] commit that deletes `scripts/main.js`
  * [ ] documentation in `docs/JS.md` for:
    * [ ] the `Array` literal type, i.e. how do I write one in various forms?
    * [ ] the magic property `length` with some examples
    * [ ] the _non-experimental_ [**Mutator Methods**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Mutator_methods), e.g. `pop()`, `push()`, `splice()`
  * [ ] commits for **String Calculator Kata** in `scripts/string-calculator.js`
  * [ ] commits for **Check Writing Kata** in `scripts/check-writing.js`
  * [ ] commits for **A Nice Game of Chess** in `scripts/main.js`
* [ ] Open PR from `feature/11--coding-dojo` to `master` with:
  * [ ] ink to your _WIP Issue_
  * [ ] 2x :+1s: from your peers
* [ ] New blog post in `USERNAME.github.io` with a permalink (e.g. `http://USERNAME.github.io/#blog-title`)...!
* [ ] Fork of [`mrdavidlaing/javascript-koans`](https://github.com/mrdavidlaing/javascript-koans) with:
  * [ ] a new branch called `first` with commits to the `koans/` directory _only_
  * [ ] an open PR from `first` to your _local_ `master` (check the **base** repo)
* [ ] Comments in your _WIP Issue_:
  * [ ] link to PR in `TIY-Assignments`
  * [ ] link to PR in `javascript-koans`
  * [ ] link to your blog post permalink

## Requirements

* the **Yak Shaving** tasks, of course!
* documentation in `docs/JS.md`
* a fork of `mrdavidlaing/javascript-koans` with an open PR
* **String Calculator** and **Check Writing** _with tests_
* _A blog post of at least 100 words..._ That's less than you think.

**Comment by jaredstevick** [comment]
Link to latest pull request:
https://github.com/jaredstevick/TIY-Assignments/pull/15

**Comment by jaredstevick** [comment]
Link to pull request: 
https://github.com/jaredstevick/javascript-koans/pull/1

**Comment by jaredstevick** [comment]
Link to blog post: (sorry no #. it's a whole separate page)
http://jaredstevick.github.io/learning-bootstrap.html
