### ISSUE TITLE
11 -- Coding Dojo Style -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#144]
## Deliverables

* _WIP Issue_ named `11 -- Coding Dojo Style` with tasks and estimates
* _WIP Branch_ named `feature/11--coding-dojo` with:
  * commit that deletes `scripts/main.js`
  * documentation in `docs/JS.md` for:
    * the `Array` literal type, i.e. how do I write one in various forms?
    * the magic property `length` with some examples
    * the _non-experimental_ [**Mutator Methods**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Mutator_methods), e.g. `pop()`, `push()`, `splice()`
  * commits for **A Nice Game of Chess** in `scripts/main.js`
  * commits for **String Calculator Kata** in `scripts/string-calculator.js`
  * commits for **Check Writing Kata** in `scripts/check-writing.js`
* Open PR from `feature/11--coding-dojo` to `master` with:
  * link to your _WIP Issue_
  * 2x :+1:s from your peers
* New blog post in `USERNAME.github.io` with a permalink (e.g. `http://USERNAME.github.io/#blog-title`)...!
* Fork of [`mrdavidlaing/javascript-koans`](https://github.com/mrdavidlaing/javascript-koans) with:
  * a new branch called `first` with commits to the `koans/` directory _only_
  * an open PR from `first` to your _local_ `master` (check the **base** repo)
* Comments in your _WIP Issue_:
  * link to PR in `TIY-Assignments`
  * link to PR in `javascript-koans`
  * link to your blog post permalink

## Requirements

**Note:** I expect you to minimally have the following to recieve credit:

* the **Yak Shaving** tasks, of course!
* more documentation in `docs/JS.md`
* a fork of `mrdavidlaing/javascript-koans` with an open PR to _your_ `master`
* **String Calculator** and **Check Writing** _with tests_
* _A blog post of at least 100 words..._ That's less than you think.

### Tasks

* [ ] **Yak Shaving** (L)
  * Merge your last PR if you haven't already! (use the merge button, Luke)
  * Pull your `master` branch locally _after_ you merge!
  * Create a new branch called `feature/11--coding-dojo`
  * Delete and commit `scripts/main.js`
  * Create and commit `scripts/string-calculator.js` and `scripts/check-writing.js`
  * Push your branch and open a PR
* [ ] **Reading JavaScript** (L)
  * [ ] Checkpoint: `Array` literals: empty and filled
  * [ ] Checkpoint: Other ways to create an `Array`?
  * [ ] Checkpoint: What's your `length`...?
  * [ ] Checkpoint: First Mutator method!
  * [ ] Checkpoint: Five Mutators down!
  * [ ] Checkpoint: What, there's only 7?
  * [ ] Mission Complete!
* [ ] **A Nice Game of Chess** (XL)
  * [ ] Checkpoint: Retyped [the example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Example:_Creating_a_two-dimensional_array) in `scripts/main.js`
  * [ ] Checkpoint: I can move pieces! Well, one, really.
  * [ ] Checkpoint: Moved _both_ sides at least once!
  * [ ] Checkpoint: Opening complete!
* [ ] **Coding Dojo** -- Time for your katas (XL)
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _my_ repo
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _another_ repo
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"ten"`! (HipChat that $#!+)
  * [ ] Checkpoint: TDD **Check Writing** from `1` to `10` in _my_ repo
  * [ ] Checkpoint: TDD **Check Writing** from `1` to `10` in _another_ repo
  * **BONUS:** TDD **Check Writing** above `20`...? (XL)
* [ ] [**JavaScript Koans**](https://github.com/mrdavidlaing/javascript-koans) (L)
  * [ ] Checkpoint: Forked and installed...!
  * [ ] Checkpoint: Ran it and it broke... as intended!
  * [ ] Checkpoint: Got `AboutExpects.js` green!
  * [ ] Checkpoint: Got `AboutArrays.js` green!
  * **BONUS:** Got `AboutFunctions.js` green! (but I'm really confused)
  * **BONUS:** Got `AboutObjects.js` green! (wasn't that bad, actually)
* [ ] **BLOG IT!** (M)

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/18

**Comment by jgarcia99** [comment]
http://jgarcia99.github.io/#JS-meets-Boot

**Comment by jgarcia99** [comment]
https://github.com/mrdavidlaing/javascript-koans/pull/41

**Comment by TaylorFoster90** [comment]
:+1:

**Comment by sak55** [comment]
:+1:

**Comment by LoganArnett** [comment]
Commits look great keep that up, just looking for the 2 :+1: to actually be on your PR not WIP issue, outside of that you're good to go
