### ISSUE TITLE
11 -- Coding Dojo Style -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#151]
### Tasks

* [ ] **Yak Shaving**
  * Merge your last PR if you haven't already! (use the merge button, Luke)
  * Pull your `master` branch locally _after_ you merge!
  * Create a new branch called `feature/11--coding-dojo`
  * Delete and commit `scripts/main.js`
  * Create and commit `scripts/string-calculator.js` and `scripts/check-writing.js`
  * Push your branch and open a PR
* [ ] **Reading JavaScript**
  * [ ] Checkpoint: `Array` literals: empty and filled
  * [ ] Checkpoint: Other ways to create an `Array`?
  * [ ] Checkpoint: What's your `length`...?
  * [ ] Checkpoint: First Mutator method!
  * [ ] Checkpoint: Five Mutators down!
  * [ ] Checkpoint: What, there's only 7?
  * [ ] Mission Complete!
* [ ] **A Nice Game of Chess**
  * [ ] Checkpoint: Retyped [the example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Example:_Creating_a_two-dimensional_array) in `scripts/main.js`
  * [ ] Checkpoint: I can move pieces! Well, one, really.
  * [ ] Checkpoint: Moved _both_ sides at least once!
  * [ ] Checkpoint: Opening complete!
* [ ] **Coding Dojo** -- Time for your katas
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _my_ repo
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"five"` in _another_ repo
  * [ ] Checkpoint: TDD **String Calculator** from `"zero"` to `"ten"`! (HipChat that $#!+)
  * [ ] Checkpoint: TDD **Check Writing** from `1` to `10` in _my_ repo
  * [ ] Checkpoint: TDD **Check Writing** from `1` to `10` in _another_ repo
  * **BONUS:** TDD **Check Writing** above `20`...?
* [ ] [**JavaScript Koans**](https://github.com/mrdavidlaing/javascript-koans)
  * [ ] Checkpoint: Forked and installed...!
  * [ ] Checkpoint: Ran it and it broke... as intended!
  * [ ] Checkpoint: Got `AboutExpects.js` green!
  * [ ] Checkpoint: Got `AboutArrays.js` green!
  * **BONUS:** Got `AboutFunctions.js` green! (but I'm really confused)
  * **BONUS:** Got `AboutObjects.js` green! (wasn't that bad, actually)
* [ ] **BLOG IT!**

**Comment by adamkarb** [comment]
[PR](https://github.com/adamkarb/TIY--Assignments/pull/11)

**Comment by adamkarb** [comment]
[Koan PR](https://github.com/adamkarb/javascript-koans/pull/1)

**Comment by adamkarb** [comment]
[Blog Post 2](https://adamkarb.github.io/#post2)

**Comment by LoganArnett** [comment]
Make sure you're committing early and often, there should be a lot more commits in there. Also keep using those tshirt estimates even if they arent required.
