### ISSUE TITLE
13 -- Lists+Dicts -- GarrettGraham

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#163]
### Tasks

* [ ] **Yak Shaving**(L)
    * [ ] Create your _WIP Issue_ named `13 -- Lists + Dicts` with tasks _and estimates!_
    * [ ] Merge your PR, update your local `master`, and open a new branch: `feature/13--lists+dicts`
    * [ ] Create a new file in `apis/github/users/USERNAME/events.json` where `USERNAME` is... you get it.
    * [ ] Use [`curl`](http://curl.haxx.se/docs/manpage.html) or [Postman](http://www.getpostman.com/) to fetch [your public events from the Github API](https://developer.github.com/v3/activity/events/#list-public-events-performed-by-a-user)
    * [ ] Commit, push, and open a PR!
* [ ] **Take a Picture**(L)
* [ ] **One More Time...**(XL)
    * [ ] Checkpoint: **String Calculator** with `if` and `return` (no `else`)
    * [ ] Checkpoint: **Check Writing** refactored to `fromEnglish()`
    * [ ] Checkpoint: **Check Writing** refactored `fromEnglish()` to use _at least one_ lookup!
    * [ ] Checkpoint: **Check Writing** with 100% `Array` lookups instead of `if`
    * [ ] Mission Complete
* [ ] **Reading JavaScript**(XL)
    * [ ] Checkpoint: Let's talk about `forEach`... a lot.
    * [ ] Checkpoint: Here's that `every()` and `some()` crowd again.
    * [ ] Checkpoint: Who needs a `filter()` anyway?
    * [ ] Checkpoint: Can I get a `map()` over here?
    * [ ] Checkpoint: I wish I could `reduce()` this assignment...
    * [ ] Checkpoint: Am I `reduceRight()`...?
    * [ ] Mission Complete!
* [ ] **API Gymnastics**(XL)
    * [ ] Checkpoint: Got me some data...
    * [ ] Checkpoint: Count it up right...
    * [ ] Checkpoint: Filtering out just the `PushEvent` entries...
    * [ ] Checkpoint: Now doing the complete opposite...
    * [ ] Checkpoint: I have all the `answers` now!
    * [ ] Mission Complete

**Comment by GarrettGraham** [comment]
## Deliverables

* [ ] _WIP Issue_ named `13 -- Lists+Dicts` with tasks _and estimates!_
* [ ] PR in `TIY-Assignments` from `feature/13--lists+dicts` to `master` with:
    * [ ] diagram of `toEnglish()` from `scripts/check-writing.js` in `docs/toEnglish.png`
    * [ ] more documentation in `docs/JS.md` for _non-experimental_ [Iteration Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Iteration_methods)
    * [ ] JSON file in `apis/github/users/USERNAME/events.json` (where `USERNAME` is _you_)
    * [ ] new file in `scripts/` called `gymnastics.js` with a function called `answers` that meets

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/pull/11

**Comment by jgarcia99** [comment]
:+1:
