### ISSUE TITLE
13 -- Lists + Dicts -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#164]
### Tasks

* [ ] **Yak Shaving** (M)
    * Create your _WIP Issue_ named `13 -- Lists + Dicts` with tasks _and estimates!_
    * Merge your PR, update your local `master`, and open a new branch: `feature/13--lists+dicts`
    * Create a new file in `apis/github/users/USERNAME/events.json` where `USERNAME` is... you get it.
    * Use [`curl`](http://curl.haxx.se/docs/manpage.html) or [Postman](http://www.getpostman.com/) to fetch [your public events from the Github API](https://developer.github.com/v3/activity/events/#list-public-events-performed-by-a-user)
    * Commit, push, and open a PR!
* [ ] **Take a Picture** (M)
* [ ] **One More Time...**(L)
    * [ ] Checkpoint: **String Calculator** with `if` and `return` (no `else`)
    * [ ] Checkpoint: **Check Writing** refactored to `fromEnglish()`
    * [ ] Checkpoint: **Check Writing** refactored `fromEnglish()` to use _at least one_ lookup!
    * [ ] Checkpoint: **Check Writing** with 100% `Array` lookups instead of `if`
    * [ ] Mission Complete
* [ ] **Reading JavaScript** (L)
    * [ ] Checkpoint: Let's talk about `forEach`... a lot.
    * [ ] Checkpoint: Here's that `every()` and `some()` crowd again.
    * [ ] Checkpoint: Who needs a `filter()` anyway?
    * [ ] Checkpoint: Can I get a `map()` over here?
    * [ ] Checkpoint: I wish I could `reduce()` this assignment...
    * [ ] Checkpoint: Am I `reduceRight()`...?
    * [ ] Mission Complete!
* [ ] **API Gymnastics** (L)
    * [ ] Checkpoint: Got me some data...
    * [ ] Checkpoint: Count it up right...
    * [ ] Checkpoint: Filtering out just the `PushEvent` entries...
    * [ ] Checkpoint: Now doing the complete opposite...
    * [ ] Checkpoint: I have all the `answers` now!
    * [ ] Mission Complete

**Comment by LoganArnett** [comment]
Need to see the link to the PR or it referenced here from dropping the WIP issue link into the PR's comments.

**Comment by carolinapowers** [comment]
[11:27 AM] Carolina Powers: https://github.com/carolinapowers/TIY-Assignments/pull/12
