### ISSUE TITLE
13 -- Lists+Dicts -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#165]
### Tasks
- [x] L **Yak Shaving** :water_buffalo: 
  - [x] Create your _WIP Issue_ named `13 -- Lists + Dicts` with tasks _and estimates!_
  - [x] Merge your PR, update your local `master`, and open a new branch: `feature/13--lists+dicts`
  - [x] Create a new file in `apis/github/users/USERNAME/events.json` where `USERNAME` is... you get it.
  - [x] Use [`curl`](http://curl.haxx.se/docs/manpage.html) or [Postman](http://www.getpostman.com/) to fetch [your public events from the Github API](https://developer.github.com/v3/activity/events/#list-public-events-performed-by-a-user)
  - [x] Commit, push, and open a PR!
- [x] M **Take a Picture** :art: 
- [x] L **One More Time...** :repeat: 
  - [x] M Checkpoint: **String Calculator** with `if` and `return` (no `else`)
  - [x] M Checkpoint: **Check Writing** refactored to `fromEnglish()`
  - [x] M Checkpoint: **Check Writing** refactored `fromEnglish()` to use _at least one_ lookup!
  - [x] M Checkpoint: **Check Writing** with 100% `Array` lookups instead of `if`
  - [x] Mission Complete
- [x] L **Reading JavaScript** :eyeglasses: 
  - [x] M Checkpoint: Let's talk about `forEach`... a lot.
  - [x] M Checkpoint: Here's that `every()` and `some()` crowd again.
  - [x] M Checkpoint: Who needs a `filter()` anyway?
  - [x] M Checkpoint: Can I get a `map()` over here?
  - [x] M Checkpoint: I wish I could `reduce()` this assignment...
  - [x] M Checkpoint: Am I `reduceRight()`...?
  - [x] Mission Complete!
- [ ] L **API Gymnastics** :muscle: 
  - [x] S Checkpoint: Got me some data...
  - [x] M Checkpoint: Count it up right...
  - [x] M Checkpoint: Filtering out just the `PushEvent` entries...
  - [ ] M Checkpoint: Now doing the complete opposite...
  - [ ] M Checkpoint: I have all the `answers` now!
  - [ ] Mission Complete

**Comment by jaredstevick** [comment]
## Deliverables

* [ ] _WIP Issue_ named `13 -- Lists+Dicts` with tasks _and estimates!_
* [ ] PR in `TIY-Assignments` from `feature/13--lists+dicts` to `master` with:
    * [ ] diagram of `toEnglish()` from `scripts/check-writing.js` in `docs/toEnglish.png`
    * [ ] more documentation in `docs/JS.md` for _non-experimental_ [Iteration Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Iteration_methods)
    * [ ] JSON file in `apis/github/users/USERNAME/events.json` (where `USERNAME` is _you_)
    * [ ] new file in `scripts/` called `gymnastics.js` with a function called `answers` that meets

**Comment by jaredstevick** [comment]
Link to current pull request:
https://github.com/jaredstevick/TIY-Assignments/pull/16
