### ISSUE TITLE
01 -- MF'g Website -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#18]
### Tasks

* [X] Create a new Issue with these tasks!
* [X] S Estimate all the tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x]  **[Try Git](http://try.github.com)** -- Rinse, Lather, Repeat...
* [x] M **The Growth and Fixed Mindsets** -- Research and Essay _notes_...
    * [x] Watch the _Growth and Fixed Mindset_ videos:
        * [_You Can Learn Anything_ by Khan Academy](https://www.khanacademy.org/youcanlearnanything) (4 videos total)
        * [_The Power of Yet_ by Carol Dweck at TED](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve),
        * [_Growth Mindsets and Motivation_ by ed-TED](http://ed.ted.com/on/UA77FlTc)
    * [x] Create a new page in your `TIY-Assignments` wiki called _Growth and Fixed Mindset_
    * [x] Write down _at least 3_ key attributes of each mindset using Markdown bullets
* [x]  M **Yak Shaving** -- The invisible tasks...
    * [x] Use the Github web interface to create a branch called `feature/01--mfg-website`
    * [x] In Github, open a PR _from_ `feature/01--mfg-website` _into_ `master`
* [x] M  **Reading HTML** -- Document 10 _block-level_ HTML elements and **commit after each!**
    * [x] Checkpoint: Created and committed `docs/HTML.md`!
    * [x] Checkpoint: First tag documented!
    * [x] Checkpoint: 5 tags documented!
    * [x] Misson Complete: All 10 tags!
* [x] L **Your MF'g Website** -- [About](http://theironyard.com/about) and [Culture](http://theironyard.com/about/culture) with **no copy-pasta!**
    * [x] Checkpoint: Created and committed `pub/about.html`!
    * [x] Checkpoint: Created and committed `pub/culture.html`!
    * [x] Checkpoint: Pushed `pub/about.html` and `pub/culture.html`!
    * [x] Checkpoint: Finished and committed `pub/about.html`!
    * [x] Checkpoint: Finished and committed `pub/culture.html`!
    * [x] Mission Complete: Finished, committed and pushed!

**Comment by jaredstevick** [comment]
:+1:

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/2

**Comment by LoganArnett** [comment]
Looks good Evan, the only thing I would tell you to start getting into the habit of if really utilizing your commit messages for more than the default of **"Updated HTML.md"** or **"Updated about.html"**, leaving a short commit message that describes what was actually updated or edited will allow you to identify errors quickly when working on more in depth projects with lots and lots of commits, but again other than that great job
