### ISSUE TITLE
15 -- Hello Lodash -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#182]
### Tasks
- [x] M **Yak Shaving** :water_buffalo: 
  - [x] S Create your _WIP Issue_ with tasks and estimates! :hourglass: 
  - [x] S Close your PR, pull `master`, open a new branch! :deciduous_tree: 
  - [x] S Add new files: :heavy_plus_sign: 
    - [x]  `scripts/3s+5s.js` :three: :five: 
    - [x]  `docs/lodash.md` : :dash: 
  - [x] S Push your branch and open a PR! 
- [ ] M **API Gymnastics** :muscle: 
  - [ ] Checkpoint: :checkered_flag: 
- [x] L **Coding Dojo** :japanese_castle:

**Comment by jaredstevick** [comment]
## Deliverables

* [ ]  _WIP Issue:_ `15 -- Hello Lodash`
* [ ] _WIP Branch:_ `TIY-Assignments:feature/15--hello-lodash` with:
  * [ ] _multiple_ commits to:
    * [ ] `scripts/3s+5s.js` -- for at least 10, 20, 30
    * [ ] `scripts/main.js` -- a better chessboard
    * [ ] `docs/lodash.md` -- documentation++
* [ ] PR in `TIY-Assignments` with:
  * [ ] 2x :+1:'s from peers
  * [ ] links to _WIP Issue_

**Comment by jaredstevick** [comment]
Link to current pull request: 
https://github.com/jaredstevick/TIY-Assignments/pull/18
