### ISSUE TITLE
15 -- Hello Lodash -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#184]
## Deliverables

* _WIP Issue:_ `15 -- Hello Lodash`
* _WIP Branch:_ `TIY-Assignments:feature/15--hello-lodash` with:
  * _multiple_ commits to:
    * `scripts/3s+5s.js` -- for at least 10, 20, 30
    * `scripts/main.js` -- a better chessboard
    * `docs/lodash.md` -- documentation++
* PR in `TIY-Assignments` with:
  * 2x :+1:'s from peers
  * links to _WIP Issue_

## Requirements

* **Yak Shaving**
* **Coding Dojos**
  * **String Calculator** with dictionary lookups in `scripts/string-calculator.js`
  * **Check Writing** with array lookups in `scripts/check-writing.js`
  * **3's and 5's** for 10, 20, 30 in `scripts/3s+5s.js`
* **Reading JavaScript** in `docs/lodash.md`
* **A Better Chessboard** in `scripts/main.js`
  * Using JavaScript to generate HTML
  * Printing HTML entities for chesspieces

### Tasks

* [ ] **Yak Shaving** (M)
  * [ ] Create your _WIP Issue_ with tasks and estimates!
  * [ ] Close your PR, pull `master`, open a new branch!
  * [ ] Add new files:
    * `scripts/3s+5s.js`
    * `docs/lodash.md`
  * [ ] Push your branch and open a PR!
* [ ] **API Gymnastics**  (L)
  * Checkpoint:
* [ ] **Coding Dojo** (XL)

**Comment by LoganArnett** [comment]
Looking for more commits and the 2 :+1: on the PR
