### ISSUE TITLE
01 -- MF'ing Website -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#20]
### Tasks

* [X] Create a new Issue with these tasks!
* [x] Estimate all the tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x] M **[Try Git](http://try.github.com)** -- Rinse, Lather, Repeat...
* [x] M **The Growth and Fixed Mindsets** -- Research and Essay _notes_...
    * [x] Watch the _Growth and Fixed Mindset_ videos:
        * [_You Can Learn Anything_ by Khan Academy](https://www.khanacademy.org/youcanlearnanything) (4 videos total)
        * [_The Power of Yet_ by Carol Dweck at TED](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve),
        * [_Growth Mindsets and Motivation_ by ed-TED](http://ed.ted.com/on/UA77FlTc)
    * [x] Create a new page in your `TIY-Assignments` wiki called _Growth and Fixed Mindset_
    * [x] Write down _at least 3_ key attributes of each mindset using Markdown bullets
* [x] M **Yak Shaving** -- The invisible tasks...
    * [x] Use the Github web interface to create a branch called `feature/01--mfg-website`
    * [x] In Github, open a PR _from_ `feature/01--mfg-website` _into_ `master`
* [x] L **Reading HTML** -- Document 10 _block-level_ HTML elements and **commit after each!**
    * [x] Checkpoint: Created and committed `docs/HTML.md`!
    * [x] Checkpoint: First tag documented!
    * [x] Checkpoint: 5 tags documented!
    * [x] Misson Complete: All 10 tags!
* [x] L **Your MF'g Website** -- [About](http://theironyard.com/about) and [Culture](http://theironyard.com/about/culture) with **no copy-pasta!**
    * [x] Checkpoint: Created and committed `pub/about.html`!
    * [x] Checkpoint: Created and committed `pub/culture.html`!
    * [x] Checkpoint: Pushed `pub/about.html` and `pub/culture.html`!
    * [x] Checkpoint: Finished and committed `pub/about.html`!
    * [x] Checkpoint: Finished and committed `pub/culture.html`!
    * [x] Mission Complete: Finished, committed and pushed!

**Comment by eklemen** [comment]
:+1:

**Comment by jgarcia99** [comment]
:+1:

**Comment by jaredstevick** [comment]
https://github.com/jaredstevick/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by jaredstevick** [comment]
Here's the pull request:
https://github.com/jaredstevick/TIY-Assignments/pull/2

**Comment by LoganArnett** [comment]
Looks good, good job on the 2 thumbs on the 2nd PR. For the **Reading HTML** or any of the other reading assignments in the future make sure you commit after each individual element like he asks. This is a good way to get into the habit of committing and saving your work often. Also make sure to be descriptive with your commit messages instead of just using the Github defaults, just something short like *added <ul> element* or *deleted thumbnail* this will allow you to identify exactly where certain errors may have occurred later on down the road if you run into a speed bump
