### ISSUE TITLE
01--MF'g website--Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#21]
### Tasks

* [X] Create a new Issue with these tasks!
* [ ] Estimate all the tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [ ] **[Try Git](http://try.github.com)** -- Rinse, Lather, Repeat...
* [ ] **The Growth and Fixed Mindsets** -- Research and Essay _notes_...
    * [ ] Watch the _Growth and Fixed Mindset_ videos:
        * [_You Can Learn Anything_ by Khan Academy](https://www.khanacademy.org/youcanlearnanything) (4 videos total)
        * [_The Power of Yet_ by Carol Dweck at TED](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve),
        * [_Growth Mindsets and Motivation_ by ed-TED](http://ed.ted.com/on/UA77FlTc)
    * [ ] Create a new page in your `TIY-Assignments` wiki called _Growth and Fixed Mindset_
    * [ ] Write down _at least 3_ key attributes of each mindset using Markdown bullets
* [ ] **Yak Shaving** -- The invisible tasks...
    * [ ] Login to Cloud 9 and open your `TIY-Assignments` workspace
    * Use the Terminal in Cloud 9 to:
        * [ ] create a branch called `feature/01--mfg-website` with `git branch`
        * [ ] switch to the branch you just created with `git checkout`
    * [ ] Create at least one file and directory as instructed.
    * [ ] Add and commit your work with `git status`, `git add`, and `git commit`
    * [ ] Push your commits to Github with `git push`
    * [ ] In Github, open a PR _from_ `feature/01--mfg-website` _into_ `master`
* [ ] **Reading HTML** -- Document 10 _block-level_ HTML elements and **commit after each!**
    * [ ] Checkpoint: Created and committed `docs/HTML.md`!
    * [ ] Checkpoint: First tag documented!
    * [ ] Checkpoint: 5 tags documented!
    * [ ] Misson Complete: All 10 tags!
* [ ] **Your MF'g Website** -- [About](http://theironyard.com/about) and [Culture](http://theironyard.com/about/culture) with **no copy-pasta!**
    * [ ] Checkpoint: Created and committed `pub/about.html`!
    * [ ] Checkpoint: Created and committed `pub/culture.html`!
    * [ ] Checkpoint: Pushed `pub/about.html` and `pub/culture.html`!
    * [ ] Checkpoint: Finished and committed `pub/about.html`!
    * [ ] Checkpoint: Finished and committed `pub/culture.html`!
    * [ ] Mission Complete: Finished, committed and pushed!

**Comment by adamkarb** [comment]
https://github.com/adamkarb/TIY--Assignments/wiki

**Comment by adamkarb** [comment]
[My Pull Request](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/21)

**Comment by jgarcia99** [comment]
:+1:

**Comment by LoganArnett** [comment]
So you linked to the general wiki page but David is looking for the link to the specific **[Growth and Fixed Mindsets](https://github.com/adamkarb/TIY--Assignments/wiki/Growth-and-Fixed-Mindset)** wiki. Also your link to your Pull Request is currently a redirect to the issue not the [PR](https://github.com/adamkarb/TIY--Assignments/pull/1). So you have everything you need and all of your code looks good just make sure you edit the links to the proper locations and that you are get 2 :+1: on each PR before you merge

**Comment by LoganArnett** [comment]
Looks good, the only other thing I will mention is to make sure you use your commit messages to be a little more specific than the default of *"Updated some.file"* for what you worked on leading up to that commit.
