### ISSUE TITLE
17-- CodeDrop JS -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#211]
### Tasks

Create a Work In Progress (WIP) Issue in this repository for every assignment
Name it according to the assignment name with your name appended, e.g. 00 -- Brace Yourself -- David Rogers
If tasks (i.e. check boxes) are provided for you in the assignment file, include them as the description of your WIP Issue
If tasks are not provided for you (as in later assignments), create your own; you will be expected to break down many assignments on your own
Estimate the complexity, difficulty, and risk of each major piece of the assignment with T-shirt sizes: Small (S), Medium (M), Large (L), Extra Large (XL)
Check off tasks as you finish to demonstrate progress; note the progress bar in the Issues list for each issue
Create a new topic branch in your TIY-Assignments repository for the assignment
Name the branch according to the assignment, e.g. 00--Brace-Yourself
Ensure that you commit all your work into that branch only
Push that branch to Github regularly to show progress
Open a Pull Request (PR) from your topic branch to master
Add a link to your WIP Issue in a comment on your Pull Request
Note that the PR will update automatically as you push more work to the branch
Do this step as soon as you have a commit; don't wait until the due date!

* **Yak Shaving**
  * [ ] Create a new _WIP Issue_ with tasks _and estimates!_
  * [ ] Create a new branch called feature/17--Codrops-Galore
  * [ ] open PR

* **Make 2 websites**
  * [ ] bootstrap
  * [ ] Mobile approach first
