### ISSUE TITLE
17 -- Codrops Galore -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#215]
### Tasks
- [x] M **Yak Shaving** :water_buffalo: 
  - [x] S Create a new _WIP Issue_ named `17 -- Codrops Galore --` 
  - [x] S With tasks and estimates :hourglass_flowing_sand: 
  - [x] S Create two new branches: :deciduous_tree: 
    - [x] S`feature/17--codrops-nested-accordion`  
    - [x] S `feature/17--codrops-full-width-tabs`
- [x] M Multiple commits
- [ ] S Immediately open  PR's
  - [x] for accordion
  - [ ] for tabs
- [ ] L Starting with HTML5 Boilerplate, modify: :hotsprings: 
  - [x] `css/main.css`
  - [x] `index.html`
  - [x] `js/main.js`
  - [ ] x2
- [ ] XL Nested Accordion Site :musical_score: 
  - [x] S Placeholder text :memo: 
  - [x] M Interactive icons :helicopter: 
  - [ ] L Show and hide paragraph text onclick :mouse: 
  - [x] M Breakpoints for media queries  :boot: 
  - [x] S Feedback from two peers :+1: 
  - [x] S Link to PR in WIP :link: 
  - [x] S Link to WIP in PR :link: 
- [ ] XL Full Width Tabs Site :corn: 
  - [x] M Tab Layout 
  - [x] S Placeholder images :art: 
  - [x] S Placeholder text :memo: 
  - [ ] M Interactive icons :helicopter: 
  - [x] M Breakpoints for media queries :iphone: 
  - [ ] L Switch content based on current tabs :twisted_rightwards_arrows: 
  - [ ] S Feedback from two peers :+1: 
  - [x] S Link to PR in WIP :link: 
  - [x] S Link to WIP in PR :link: 
- [ ] XL Beast Mode
  - [ ] Find a more intuitive way to show and hide text :trollface:

**Comment by jaredstevick** [comment]
Link to PR for nested accordion: 
https://github.com/jaredstevick/TIY-Assignments/pull/19

**Comment by jaredstevick** [comment]
Link to PR for full width tabs site:
https://github.com/jaredstevick/TIY-Assignments/pull/20
