### ISSUE TITLE
01 -- MF'g Website -- Taylor Foter

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#23]
### Tasks

* [X] Create a new Issue with these tasks!
* [x] Estimate all the tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x]  XL **[Try Git](http://try.github.com)** -- Rinse, Lather, Repeat...
* [x] M **The Growth and Fixed Mindsets** -- Research and Essay _notes_...
    * [x] S Watch the _Growth and Fixed Mindset_ videos:
        * [_You Can Learn Anything_ by Khan Academy](https://www.khanacademy.org/youcanlearnanything) (4 videos total)
        * [_The Power of Yet_ by Carol Dweck at TED](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve),
        * [_Growth Mindsets and Motivation_ by ed-TED](http://ed.ted.com/on/UA77FlTc)
    * [x] M Create a new page in your `TIY-Assignments` wiki called _Growth and Fixed Mindset_
    * [x] M Write down _at least 3_ key attributes of each mindset using Markdown bullets
* [x] XL **Yak Shaving** -- The invisible tasks...
    * [x] XL Use the Github web interface to create a branch called `feature/01--mfg-website`
    * [x] XL In Github, open a PR _from_ `feature/01--mfg-website` _into_ `master`
* [x] L **Reading HTML** -- Document 10 _block-level_ HTML elements and **commit after each!**
    * [x] L Checkpoint: Created and committed `docs/HTML.md`!
    * [x] L Checkpoint: First tag documented!
    * [x] L Checkpoint: 5 tags documented!
    * [x] L Misson Complete: All 10 tags!
* [x] XL **Your MF'g Website** -- [About](http://theironyard.com/about) and [Culture](http://theironyard.com/about/culture) with **no copy-pasta!**
    * [x]  L Checkpoint: Created and committed `pub/about.html`!
    * [x] L Checkpoint: Created and committed `pub/culture.html`!
    * [x] L Checkpoint: Pushed `pub/about.html` and `pub/culture.html`!
    * [x] L Checkpoint: Finished and committed `pub/about.html`!
    * [x] L Checkpoint: Finished and committed `pub/culture.html`!
    * [x] L Mission Complete: Finished, committed and pushed!

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/1

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/1

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/tree/feature/01--mfg-website/pub

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by jgarcia99** [comment]
:+1:

**Comment by LoganArnett** [comment]
Good job man, you were very specific with your early commits but then fell back to the default of just *"Updated some.file"*, make sure to always use that message to let yourself know what you are working on, you're having a conversation with your future self to let you know what was changed to potentially save yourself a lot of time when looking for problems in the code

Other than that it looks great man :+1:
