### ISSUE TITLE
19 -- Even More jQuery -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#235]
# Tasks
### Yak Shaving M :water_buffalo:
- [x] S Merge previous branch
- [x] S Create new branch `19 -- Even More jQuery`
- [x] S Clean Slate
- [ ] S 2x Feedback
- [x] S Link to WIP in PR
- [x] S Link to PR in WIP
- [x] S Tasks and estimates
### Github Profile Site L
- [x] S H5BP & Bootstrap
- [ ] S Responsive Layout
- [ ] M Mobile and Desktop Views
- [ ] S Links and Icons
- [x] M Tabs
- [ ] S Placeholder text and images
### jQuery L
- [ ] M Documentation
- [ ] L Codeschool
### MVC ToDo List XL
- [x] Teamwork makes the dream work
- [x] Multiple commits from each team member
- [x] Feature branches and PR's with feedback
- [x] As much functionality as possible
## Requirements
- _WIP Issue:_ `19 -- Even More jQuery`
- _WIP Branch:_
  - `TIY-TodoMVC:master` (as before)
  - `TIY-Assignments:feature/19--more-jquery`
- **Getting _More_ Things Done**
  - Same as yesterday!
- **Github Profile**
  - Blow up that `pub/` again!
  - Start with...? _H5BP!_
  - Use Bower to install Bootstrap + jQuery
  - Get to work!

**Comment by jaredstevick** [comment]
Link to current PR:
https://github.com/jaredstevick/TIY-Assignments/pull/22

**Comment by LoganArnett** [comment]
Looking for some more commits and the :+1:'s on that PR
