### ISSUE TITLE
20 -- Github Revolution -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#255]
## Tasks
- [x] M Yak Shaving
  - [x] New WIP `20 -- Github Revolution --`with features and estimates
  - [x] Merge existing branch
  - [x] New feature branch `feature/20--github-revolution`
  - [x] Fix merge conflict (as usual)
- [x] Start with yesterday's html
  - [ ] L Match Github mobile and desktop layouts
  - [x] L Placeholder text/data sections
  - [x] S Create `.json` file in `apis/github/users/`
  - [x] L Populate page with user data
  - [x] L Create and store comments on WIP issue
  - [x] M Disallow empty comments
  - [x] M Update comments without page refresh
  - [ ] Feedback from 2 peers
  - [x] Link to PR in WIP
  - [x] Link to WIP in PR
- [ ] XL Attempt Beast Mode
  - [ ] Populate profile with data from the live API for any username
- [ ] XXXXXL Research Nightmare mode (not likely to do anything with it, but it might be nice to learn about what it would require
- [x] Get some f'ing sleep
## Requirements
- _WIP Issue:_ `20 -- Github Revolution`
- _WIP Branch:_ `feature/20--github-revolution`
- **Insert Profile Data Here**
  - Use yesterday's HTML
  - Create `.json` files in `apis/github/users/`
  - Use `jQuery.get()` et al
  - Populate page with _your_ data
- **We Value Your Comments**
  - Load and store comments on your _WIP Issue_
  - Form should _not_ submit empty comments
  - Update comments without a page refresh

**Comment by jaredstevick** [comment]
Link to current PR:
https://github.com/jaredstevick/TIY-Assignments/pull/23

**Comment by jaredstevick** [comment]
TESTING

**Comment by jaredstevick** [comment]
let's try this again

**Comment by jaredstevick** [comment]
do i need to refresh?

**Comment by jaredstevick** [comment]
words

**Comment by jaredstevick** [comment]
hi

**Comment by jaredstevick** [comment]
..

**Comment by jaredstevick** [comment]
test

**Comment by jaredstevick** [comment]
test

**Comment by jaredstevick** [comment]
test

**Comment by jaredstevick** [comment]
test

**Comment by jaredstevick** [comment]
testing

**Comment by jaredstevick** [comment]
testing comment box

**Comment by jaredstevick** [comment]
test

**Comment by jaredstevick** [comment]
commenting in the matrix
