### ISSUE TITLE
21 -- Night of the Living Chessboard -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#263]
## Tasks
- [x] Yak Shaving :water_buffalo: 
  - [x] Merge feature 20
  - [x] Start with existing chessboard
- [x] Link to PR in WIP
- [x] Link to WIP in PR
- [ ] 2x Peer review
- [ ] Review previous assignments as time permits
## Color Clock
- [x] Use setInterval()
- [x] color changes each second
- [x] make it look awesome
## F'in Chessboard -for Wednesday
- [x] User stories
- [ ] Use constructors and prototypes
- [ ] Replicate previous moves
- [ ] Add more moves including castling and captures
- [ ] Buttons progress through moves
- [ ] Maybe try to keep score?

**Comment by jaredstevick** [comment]
## Chessboard User Stories:
* As a smurf, I can start a Game so that smurfs can play Chess

* Board with:
  * 8 rows and 8 columns with squares of alternating colors, light and dark
  * Pieces:
  * 32x pieces: 16 for each color light and dark in starting position
      * 8x pawns
      * 2x rooks
      * 2x bishops
      * 2x knights
      * 1 queen
      * 1 king
* As a Player, I can play a Game so that Players can play chess
  * 2x Players - one per color
  * How do you choose the color for each player?
    * Randomly assign a color to each player?
    * Each player could choose their color?    

As a smurf, I can move a Piece so that I can play my turn.
  * Piece starts at position - rank and file
  * Piece moves to new position - rank and file
  * What happens when piece moves to occupied space?
  * Players alternate turns
  * Board only contains pieces that have not been captured in previous turns

**Comment by jaredstevick** [comment]
Link to current PR:
https://github.com/jaredstevick/TIY-Assignments/pull/24

**Comment by LoganArnett** [comment]
Looking for some fiddling with the Chessboard and 1 more :+1:
