### ISSUE TITLE
01 -- MFg-Website -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#27]
### Tasks

* [X] Create a new Issue with these tasks!
* [x] Estimate all the tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_ --S
* [x] **[Try Git](http://try.github.com)** -- Rinse, Lather, Repeat... --M
* [x] **The Growth and Fixed Mindsets** -- Research and Essay _notes_... -- S
    * [x] Watch the _Growth and Fixed Mindset_ videos:
        * [_You Can Learn Anything_ by Khan Academy](https://www.khanacademy.org/youcanlearnanything) (4 videos total)
        * [_The Power of Yet_ by Carol Dweck at TED](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve),
        * [_Growth Mindsets and Motivation_ by ed-TED](http://ed.ted.com/on/UA77FlTc)
    * [x] Create a new page in your `TIY-Assignments` wiki called _Growth and Fixed Mindset_
    * [x] Write down _at least 3_ key attributes of each mindset using Markdown bullets
* [x] **Yak Shaving** -- The invisible tasks... --S
    * [x] Use the Github web interface to create a branch called `feature/01--mfg-website`
    * [x] In Github, open a PR _from_ `feature/01--mfg-website` _into_ `master`
* [x] **Reading HTML** -- Document 10 _block-level_ HTML elements and **commit after each!** --L
    * [x] Checkpoint: Created and committed `docs/HTML.md`!
    * [x] Checkpoint: First tag documented!
    * [x] Checkpoint: 5 tags documented!
    * [x] Misson Complete: All 10 tags!
* [x] **Your MF'g Website** -- [About](http://theironyard.com/about) and [Culture] --L (http://theironyard.com/about/culture) with **no copy-pasta!**
    * [x] Checkpoint: Created and committed `pub/about.html`!
    * [x] Checkpoint: Created and committed `pub/culture.html`!
    * [x] Checkpoint: Pushed `pub/about.html` and `pub/culture.html`!
    * [x] Checkpoint: Finished and committed `pub/about.html`!
    * [x] Checkpoint: Finished and committed `pub/culture.html`!
    * [x] Mission Complete: Finished, committed and pushed!

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/27

**Comment by jrutishauser** [comment]
[Growth and Fixed Mindset wiki](https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset)

**Comment by jgarcia99** [comment]
:+1:

**Comment by LoganArnett** [comment]
Looks great Jon, keep up the great commit messages it will definitely help you in any project you do to have those little hints for yourself

**Comment by jrutishauser** [comment]
@LoganArnett thanks, anything that needs more work with this? Should I specifically review anything?

**Comment by al-the-x** [comment]
Feedback registered on your PR, sir. If you wanna take another swing at that MF'g Website, I'll look at it again in a subsequent PR.
