### ISSUE TITLE
22 -- Vue from the Top -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#277]
## Tasks
- [x] S Yak Shaving :water_buffalo: 
  - [x] Merge previous branch
  - [x] New branch - feature 22
  - [x] Use old chessboard
  - [x] Tasks and estimates
- [x] L Attack of the Killer Prototypes
  - [x] In scripts/pieces.js
  - [x] Implement `Piece` Constructor and its Prototype
  - [x] Include tests
- [ ] XL Night of the Living Chessboard
  - [ ] Modify main.js, index.html, and main.css
  - [ ] Get board working with jQuery
- [x] Link to WIP in PR
- [x] Link to PR in WIP
- [ ] 2x Peer Feedback
## Requirements
- _WIP Issue:_ `22 -- Vue from the Top`
- _WIP Branch:_ `feature/22--vue-from-the-top`
- _WIP Files:_
  - **Attack of the Killer Prototypes**
    - `scripts/pieces.js`
  - **Night of the Living Chessboard**
    - `pub/index.html`
    - `pub/js/main.js`
    - `pub/css/main.scss`
    - `pub/css/main.css`

**Comment by jaredstevick** [comment]
Link to current PR:
https://github.com/jaredstevick/TIY-Assignments/pull/25

**Comment by LoganArnett** [comment]
Just looking for some :+1:'s on that PR
