### ISSUE TITLE
24 -- Helluva Ride -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#299]
## Tasks
- [x] M Shave all the yaks :water_buffalo: 
  - [x] Merge existing branch
  - [x] Create new branch `feature/24--helluva-ride`
  - [x] New WIP - 24--helluva-ride with tasks and estimates
  - [ ] Folder structure
- [x] S Links to each PR in WIP comments
- [x] S Link to WIP in each PR
- [x] S 2x peer review on each PR
- [x] S Create index.md in directory root with links to each index file
## Assignments
- [x] L Responsive Vertical Timeline
  - [x] M Mobile first design
  - [x] M Tablet and full size breakpoints
  - [x] S MF'ing HTML
  - [x] S CSS
  - [x] S Glyph icons
  - [x] S Stupid carets
  - [x] M Update bug fixes periodically 
- [x] L String Calculator
  - [x] S `"zero"` through `"ten"`
  - [x] S `"ten"` through `"twenty"`
  - [x] M `"twenty"` through `"thirty"`
  - [x] M `"fifty"` through `"sixty"`
  - [x] M `"ninety"` through `"one hundred"`
  - [x] M `"one hundred"` through `"one hundred twenty"`
- [ ] L Check Writing
  - [x] S `"zero"` through `"ten"`
  - [x] S `"ten"` through `"twenty"`
  - [ ] M `"twenty"` through `"thirty"`
  - [ ] M `"fifty"` through `"sixty"`
  - [ ] M `"ninety"` through `"one hundred"`
  - [ ] M `"one hundred"` through `"one hundred twenty"`
- [x] L API Gymnastics
  - [x] S Checkpoint: Got me some data...
  - [x] S Checkpoint: Count it up right...
  - [x] S Checkpoint: Filtering out just the `PushEvent` entries...
  - [x] S Checkpoint: Now doing the complete opposite...
  - [x] M Checkpoint: I have all the `answers` now!
  - [x] M Mission Complete
- [x] XL Surf & Paddle RWD
  - [x] S MFing HTML
  - [x] M Mobile Layout
  - [x] M Tablet Layout
  - [x] M Desktop Layout
- [ ] XL Github Profile
  - [ ] L Responsive layout
  - [ ] L Mobile and desktop views
  - [ ] M Get data
  - [ ] L Populate page with data
  - [x] M Comment box
    - [x] comments recorded in location tbd
    - [ ] enable login?
- [ ] XL Chessboard
  - [ ] M Build chessboard with js or html
  - [ ] L Place pieces on board
  - [ ] L Make pieces move
  - [ ] L Buttons for
    - [ ] S One move forward
    - [ ] S One move backward
    - [ ] S Play all remaining moves
    - [ ] S Reset sequence
    - [ ] S Pause
  - [ ] L Replicate moves of Catalan opening
## Requirements
- _WIP Issue:_ `24 -- Helluva Ride`
  - checklist of assignments and checkpoints
  - link to each PR you merge
- _WIP Branch:_
  - work in: `TIY-Assignments:feature/24--helluva-ride`
  - deploy into: `TIY-Assignments:gh-pages`
- _WIP Files:_
  - `timeline/index.html`
  - `surf+paddle/index.html`
  - `katas/`
    - `string-calculator.js`
    - `check-writing.js`
    - `roman-numerals.js`
    - `euler-1.js` -- formerly `3s+5s.js`
    - `euler-2.js` -- even Fibonacci
    - `euler-4.js` -- largest palindrome
    - `euler-5.js` -- smallest multiple
  - `apis/gymnastics.js`
  - `chessboard/`
    - `index.html`
    - `css/main.css`
    - `js/main.js`
  - `github/`
    - `index.html`
    - `css/main.css`
    - `js/main.js`

**Comment by jaredstevick** [comment]
## Timeline bugfixes
* [ ] TBD

**Comment by jaredstevick** [comment]
First PR for Vertical Timeline:
https://github.com/jaredstevick/TIY-Assignments/pull/26

**Comment by jaredstevick** [comment]
## Katas Known Issues 
* [ ] String calculator solution is super hacky and could be refactored
* [ ] Check writing only returns numbers up to 20
  * [ ] still need to return the numbers as words in check format

**Comment by jaredstevick** [comment]
PR for API Gymnastics:
https://github.com/jaredstevick/TIY-Assignments/pull/29

## API Gymnastics Known Issues
* [ ] What other data can I pull?
* [ ] Everything could probably be refactored a bit to be cleaner

**Comment by jaredstevick** [comment]
PR for Surf & Paddle: 
https://github.com/jaredstevick/TIY-Assignments/pull/30

## Surf & Paddle Known Issues

**Comment by jaredstevick** [comment]
PR for Github Page:
https://github.com/jaredstevick/TIY-Assignments/pull/31

**Comment by LoganArnett** [comment]
62 Checkboxes!!! :+1:'s everywhere on those PR's, only one needing some love is the Github PR

**Comment by jaredstevick** [comment]
hi

**Comment by jaredstevick** [comment]
here's a comment sent from the github profile page
