### ISSUE TITLE
02 -- Learning Layout -- Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#32]
### Tasks

* [x] **Yak Shaving** -- There's always one more...
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] **Draft Outline** -- 4 main sections
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [x] **Read [Learn Layout](http://learnlayout.com)**
* [x] **Reading CSS** -- Document the CSS properties presented in "Learn Layout"
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [x] Checkpoint: 10 CSS properties committed and pushed!
    * [x] Mission Complete: You know layout!
* [x] **Reading HTML** -- Part deaux: _10 more tags!_
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [ ] **The Iron Blog** -- It doesn't have to be complicated...
    * [ ] Page header with placeholder image, logo
    * [ ] Page footer with logo and links
    * [ ] Side column with headings and links
    * [ ] Main column:
        * [ ] 3 articles with headings and placeholder text
        * [ ] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/2

**Comment by LoganArnett** [comment]
Looks good Taylor, one slight syntax issue starting at HTML element number 16, other than that you're good to go, start building out that blog

**Comment by al-the-x** [comment]
I feel like you could have a stronger conclusion in your outlne, but I also recognize you might just need some more time with it. Keep refining, and look for opportunities to work in personal stories. This essay is mostly for self-discovery.

**Comment by al-the-x** [comment]
Now that you're neck-deep in **The Iron Blog, Take 2**, I'm sure you wish you had allocated a little more time to the first pass of **The Iron Blog**. Take this as a lesson: estimate, prioritize, and allocate time for _every piece_ of the assignment. Don't save the bigguns for last.
