### ISSUE TITLE
25 -- Something Beautiful -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#325]
turns out when you have too many tabs open, it's easy to forget you never clicked submit on your last WIP.  whoops.
## Tasks
- [x] Formulate a Plan
- [x] Yak Shaving
- [x] MF'ing html
- [x] Style with css
- [x] Pull user location from google maps api
- [x] pull weather for specific location from forecast.io
- [ ] Populate page data with results
## Requirements
- _WIP Issue:_ `25 -- Something Beautiful`
  - link to issue 1 in repo `TIY-Mashup` with title `Planning`
  - links to _all_ PRs in `TIY-Mashup` repo
  - link to deployment URL
- _WIP Branch:_ in _new_ repo named `TIY-Mashup`
  - work in: `TIY-Mashup:feature/*`
  - merge to: `TIY-Mashup:master`
  - deploy to: `TIY-Mashup/gh-pages`
- _WIP Files:_
  - Start with H5BP -- maybe use [`generator-gulp-webapp`](http://j.mp/17idlew)?
  - At least _two (2)_ [APIs](../APIs.md)
  - Try using [`hello.js`](http://adodson.com/hello.js/) for Authentication?

**Comment by jaredstevick** [comment]
Link to repo:
https://github.com/TaylorFoster90/TIY-Mashup

**Comment by jaredstevick** [comment]
Planning:  

# TIY-Mashup
This is going to b-e-a-u-tiful

Start Page
* Input zip code -> convert to lat & long
* Google maps or built in?
* automatically determined?

Use lat/long to pull weather for current location
* use input to request local weather

Weather icons displayed dependent upon forecasted conditions
* determine which icons correspond to specific weather events
 
Background image changes based on current weather/temperature
* maybe just background colors?

Mobile, tablet, and desktop layouts
