### ISSUE TITLE
29 -- Brand New Day -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#333]
## Tasks for Etsy Product Catolog
- [x] M Yak shaving
- [x] M User stories for horizontal slide-out menu
  - [x] brainstorm on whiteboards
  - [x] transcribe into wiki
  - [ ] open PR for `README.md`
- [ ] L Start html and css for horizontal slide-out menu layout
- [ ] S fork [`TIY-Catalog`](https://github.com/TheIronYard--Orlando/TIY-Catalog)
  - [ ] copy `index.html` (from H5BP) into:
  - [ ] `menu.html`: [Horizontal Slide-Out Menu](http://tympanus.net/Blueprints/HorizontalSlideOutMenu/)
  - [ ] `products.html`: [View Mode Switch](http://tympanus.net/Blueprints/ViewModeSwitch/)
  - [ ] `product.html`: [Responsive Product Grid](http://tympanus.net/Blueprints/ProductGridLayout/)
  - [ ] M make corresponding SCSS/CSS files
  - [ ] M use `node-sass scss/*.scss --output css/` to build CSS
- [ ] L Look into API data for Etsy
  - [ ] M start munging data into usable chunks
  - [ ] M fetch JSON into `TIY-Assignments:apis/etsy/` for
  - [ ] S products (listings) -- trending only?
  - [ ] S product options (variations)
  - [ ] S categories (taxonomy)
  - [ ] S stores
- [x] M Codeschool Angular lessons 1-2 w/o buying answers
  - [x] transcribe code in `TIY-Assignments:pub/`

**Comment by jrutishauser** [comment]
http://static.fjcdn.com/gifs/Haters+gonna+hate_884d4c_4250947.gif

**Comment by jaredstevick** [comment]
Link to PR:
https://github.com/jaredstevick/TIY-Assignments/pull/32
