### ISSUE TITLE
29 -- Brand New Day -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#336]
## Tasks for Etsy Product Catolog
  * [ ] M Yak shaving
  * [ ] M User stories for horizontal slide-out menu
    * [ ] brainstorm on whiteboards
    * [ ] transcribe into wiki
    * [ ] open PR for `README.md`

* [ ] L Start html and css for horizontal slide-out menu layout
* [ ] S fork [`TIY-Catalog`](https://github.com/TheIronYard--Orlando/TIY-Catalog)
  * [ ] copy `index.html` (from H5BP) into:
  * [ ] `menu.html`: [Horizontal Slide-Out Menu](http://tympanus.net/Blueprints/HorizontalSlideOutMenu/)
  * [ ] `products.html`: [View Mode Switch](http://tympanus.net/Blueprints/ViewModeSwitch/)
  * [ ] `product.html`: [Responsive Product Grid](http://tympanus.net/Blueprints/ProductGridLayout/)
  * [ ] M make corresponding SCSS/CSS files
  * [ ] M use `node-sass scss/*.scss --output css/` to build CSS

* [ ] L Look into API data for Etsy
  * [ ] M start munging data into usable chunks
  * [ ] M fetch JSON into `TIY-Assignments:apis/etsy/` for
  * [ ] S products (listings) -- trending only?
  * [ ] S product options (variations)
  * [ ] S categories (taxonomy)
  * [ ] S stores

* [ ] M Codeschool Angular lessons 1-2 w/o buying answers
  * [ ] transcribe code in `TIY-Assignments:pub/`

**Comment by jaredstevick** [comment]
what a dick
