### ISSUE TITLE
29 -- Brand New Day -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#339]
## Tasks for Etsy Product Catolog
- [x]  Yak shaving
- [x]  User stories for horizontal slide-out menu
  - [x] brainstorm on whiteboards
  - [x] transcribe into wiki
  - [ ] open PR for `README.md`
- [ ]  fork [`TIY-Catalog`](https://github.com/TheIronYard--Orlando/TIY-Catalog)
  - [ ] copy `index.html` (from H5BP) into:
  - [ ] `menu.html`: [Horizontal Slide-Out Menu](http://tympanus.net/Blueprints/HorizontalSlideOutMenu/)
  - [x] `products.html`: [View Mode Switch](http://tympanus.net/Blueprints/ViewModeSwitch/)
  - [ ] `product.html`: [Responsive Product Grid](http://tympanus.net/Blueprints/ProductGridLayout/)
  - [ ]  make corresponding SCSS/CSS files
  - [ ]  use `node-sass scss/*.scss --output css/` to build CSS
- [ ]  Look into API data for Etsy
  - [ ]  start munging data into usable chunks
  - [ ]  fetch JSON into `TIY-Assignments:apis/etsy/` for
  - [ ]  products (listings) -- trending only?
  - [ ]  product options (variations)
  - [ ]  categories (taxonomy)
  - [ ]  stores
- [x]  Codeschool Angular lessons 1-2 w/o buying answers
  - [ ] transcribe code in `TIY-Assignments:pub/`
