### ISSUE TITLE
HausBrewer -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#362]
## Phase 1
- [x] Begin Planning, define precise MVP
- [x] Define necessary tech at bottom
- [x] set timeline for project with checkpoints
- [x] choose the appropriate generator
- [x] shave that yak! get those dependencies!
  - [x] git flow
- [ ] get comfortable with karma and jasmine test to start driving tests during development
## MVP (so far)
- [x] create basic website layout
- [x] mobile first!
- [x] capability for a recipe to be input
- [x] ability to take that recipe and create a step by step brew process
  - [x] initially no major measurements, step by step generated will be generic
- [x] capability for a user to login and see their recipes they have input
- [x] 2 storage zones, recipes and brewed batches of beer, maybe 3
- [ ] notes blank
## Stretch goal 1
- [ ]  fermentation schedule can be added to google calendar or iphone calendar(maybe both)
- [ ] input from brewers everywhere for what to add!
## Stretch goal 2
- [ ] start getting more detailed with information that can be input
  - [ ] gravity readings
  - [ ] temperature readings 
  - [ ] start calculating brewhouse efficiency
- [ ] input from brewers everywhere for what to add!
## Stretch goal 3
- [ ] temperature of water needed can be derived from average room temperature and target grain steep temperature
- [ ] more ridiculous measurements like this
- [ ] input from brewers everywhere for what to add!
## Stretch goal 4
- [ ] input from brewers everywhere for what to add!
## Necessary Tech
- [x] HTML/CSS
- [x] SCSS
- [x] Javascript
- [x] Angular.js
- [x] Firebase / Angularfire
- [x] dependency tools, Npm / Bower / Wiredep
- [x] things that make our life easier, Gulp / Browser-sync / Yeoman generator / git flow
- [ ] Karma and Jasmine for testing
- [x] Chrome Developer Tools

**Comment by jrutishauser** [comment]
Burndown Chart: https://dl.dropboxusercontent.com/u/24946374/Screen%20Shot%202015-03-10%20at%2011.18.46%20AM.png

**Comment by jrutishauser** [comment]
Burndown Chart Friday the 13th. A little bit behind schedule, made some decent strides though so I think I can get back on track this weekend. https://dl.dropboxusercontent.com/u/24946374/Screen%20Shot%202015-03-13%20at%203.04.06%20PM.png

can login just need to access the information from the facebook ID

**Comment by al-the-x** [comment]
How about a link to your repo?

**Comment by jrutishauser** [comment]
Oops @al-the-x  https://github.com/jrutishauser/hausbrewer

**Comment by jrutishauser** [comment]
https://dl.dropboxusercontent.com/u/24946374/Screen%20Shot%202015-03-16%20at%209.40.06%20PM.png still 1 day behind my target :/, providing I dont get stuck on something else, lolololol

**Comment by jrutishauser** [comment]
Notes blank for brewer notes about recipe was brought to my attention by a fellow brewer, love the idea.  This is a physical note so I remember why and dont forget

**Comment by al-the-x** [comment]
Lobe that you're already getting customer feedback and valuation from others on this, Jon. Keep it up!

**Comment by al-the-x** [comment]
Also noticed that you've been committing your `*.sw{o,p}` files by accident.

**Comment by al-the-x** [comment]
It would also be easier to help and review your work if you were opening issues or at least PRs in your repo.

**Comment by jrutishauser** [comment]
first build. everything works great except ng-include header decided to not show up to the party http://jrutishauser.github.io/hausbrewer/dist/#/landing/recipe

@al-the-x 

also need to start styling this thing very soon.

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/1

first PR for feature closed. Man, git flow makes all of this quite a bit easier by automating so much @al-the-x

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/2

merging release 1.0.0 to master

**Comment by jrutishauser** [comment]
hopefully im doing this properly :laughing:

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/3

**Comment by jrutishauser** [comment]
https://hausbrewer.firebaseapp.com/#/

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/5 style!

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/issues/6 FIXES / BUGS

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/7

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/hausbrewer/pull/9
