### ISSUE TITLE
00 -- Brace Yourself -- BEN GRIFFITH

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/FEE--2015--SPRING#380]
#00 -- Brace Yourself... It's gonna be a bumpy ride.

Most of this assignment is getting your laptop ready for Day 1 by installing a few key pieces of software and registering for certain invaluable services like Github and Slack. Beyond that, you'll start to get familiar with Github and basic source control concepts that we'll be using throughout the class. These aren't specific to any language or toolkit; they're universal developer skills.
## Requirements

Click on this file in Github and use the **Raw** button to see the unrendered Markdown text. If you copy and paste the text _as is_ from the **Tasks** and **Deliverables** sections below into the **Description** of your issue, you should end up with a bunch of checkboxes, just like these, thanks to [the way that Github interprets Markdown](https://guides.github.com/features/mastering-markdown/). As you complete tasks, check off the corresponding checkboxes and what your progress bar fill! Read [Mastering Issues](https://guides.github.com/features/issues/) for more information on creating issues in Github.
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING)
- [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/wiki)
- [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/new)
  - [x] Named `00 -- Brace Yourself -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`; Don't Panic.
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [x] Using the `brew` command, install the following packages:
  - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `node`
- [x] Add the output of the following commands as comments on your _WIP Issue_:
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [x] Install the following (bonus if you use `brew`):
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Dash](http://kapeli.com/dash)
  - [ ] [Slack](http://www.slack.com)
  - [x] [Atom](http://atom.io)
- [ ] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [ ] Add a link to your new Github repo as a comment on your _WIP Issue_
- [x] Create a new repository called `TIY-Assignments`
  - [ ] Check the box to create an initial `README.md` file
  - [ ] Select the `CC0` -- "Creative Commons" license for your work
  - [ ] Add a link to your `TIY-Assignments` repo as a comment on your _WIP Issue_
- [ ] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [ ] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] Install Prezto
  - [ ] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [ ] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [ ] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
  - [ ] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
  - [ ] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
### Deliverables:
- [x] _WIP Issue_
  - [x] named `00 -- Brace Yourself -- YOUR NAME`
  - [x] with description matching **Tasks**
- [x] A Github Profile with:
  - [x] Intelligible picture of yourself
  - [x] Your full name
  - [x] A valid email address
- [x] Comments on your _WIP Issue_ with output from
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [ ] Comments on your _WIP Issue_ with links to your repos for
  - [ ] `Hello-World`
  - [ ] `TIY-Assignments`
  - [ ] `Fork-and-Spoon`
  - [ ] `prezto`
## Extracurricular Activities

Regardless of how good you think you are at typing, a lot of the mistakes you make at first will be simple typographic errors. If you _don't_ know how to touch type (i.e. without looking at the keyboard), start practicing _now_ with http://www.keybr.com/. If you're fairly confident in your typing ability, try working through the JavaScript lessons on http://typing.io

As I recommended to you in your interviews, there are two books that I suggest you start reading. They're both avaialble in digital format on various devices, and they're both relatively easy reads:
- [_Getting Things Done_ by David Allen](http://j.mp/134jABk)
- [_Pragmatic Thinking and Learning_ by Andy Hunt](http://j.mp/1D5nmu8)

**Comment by BFGriffith** [comment]
/usr/local/bin/zsh
zsh 5.0.7 (x86_64-apple-darwin14.0.0)

/usr/local/bin/git
git version 2.3.6

/usr/local/bin/hub
git version 2.3.6
hub version 2.2.1

/usr/local/bin/node
v0.12.2
