### ISSUE TITLE
02 -- Learning Layout -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#39]
#### Tasks
 
+ [x] **Yak Shaving** -- There's always one more...(L)
+    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
+    * [X] Add these checkboxes as the description!
+    * [X] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
+    * [X] Clone your `TIY-Assignments` repository into a new Workspace and open it
+    * [X] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
+    * [X] Create a new file in `docs/` called `CSS.md` and commit it. (L)
+    * [X] Create a new file in `pub/` called `index.html` and commit it. (L)
+    * [X] Push your branch into the `origin` remote. (L)
+    * [X] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master` (L)
+ [x] **Draft Outline** -- 4 main sections (M)
+    * [x] Introduction
+    * [x] 3 main points
+    * [x] Conclusion
+    * [x] Add link to _WIP Issue_!
* [x] **Read [Learn Layout](http://learnlayout.com)**
* [x] **Reading CSS** -- Document the CSS properties presented in "Learn Layout"
+    * [x] Checkpoint: First CSS property committed and pushed!
+    * [x] Checkpoint: 5 CSS properties committed and pushed!
+    * [x] Checkpoint: 10 CSS properties committed and pushed!
+    * [x] Mission Complete: You know layout!
+ [x] **Reading HTML** -- Part deaux: _10 more tags!_ (M)
+    * [x] Checkpoint: Here's number 11!
+    * [x] Checkpoint: 15 done, committed, and pushed!
+    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
+ [ ] **The Iron Blog** -- It doesn't have to be complicated... (XL)
+    * [x] Page header with placeholder image, logo
+    * [x] Page footer with logo and links
+    * [x] Side column with headings and links
+    * [x] Main column:
+        * [x] 3 articles with headings and placeholder text
+        * [x] 3 placeholder images
+        **bonus** -- article footer + icons!

 #### Format for _Reading CSS_

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/2

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
Looks good Carolina, you may want to format your issues a little further so that you can see the prioritization of each task instead of just straight checkboxes all the way down. Also check to make sure there are no syntax issues on your wiki. Everything looks good and start working on that blog

**Comment by al-the-x** [comment]
Use the "Raw" button to view [the Markdown version of the Assignment file](https://raw.githubusercontent.com/TheIronYard--Orlando/FEE--2015--SPRING/master/Assignments/02--Learning-Layout.md) when you copy and paste your task list. This will keep the formatting and indentation the same.
