### ISSUE TITLE
02 -- Learning Layout -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#41]
#### Tasks

* [x] **Yak Shaving** -- There's always one more...(All in Cloud9) 1...M
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] **Draft Outline** -- 4 main sections 5 ... M
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [x] **Read [Learn Layout](http://learnlayout.com)** 2 ... S
* [x] **Reading CSS** -- Document the CSS properties presented in "Learn Layout" 3 ... L
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [x] Checkpoint: 10 CSS properties committed and pushed!
    * [x] Mission Complete: You know layout!
* [x] **Reading HTML** -- Part deaux: _10 more tags!_ 4 ... L
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [ ] **The Iron Blog** -- It doesn't have to be complicated... 6 ... M
    * [ ] Page header with placeholder image, logo
    * [ ] Page footer with logo and links
    * [ ] Side column with headings and links
    * [ ] Main column:
        * [ ] 3 articles with headings and placeholder text
        * [ ] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by sak55** [comment]
https://github.com/sak55/TIY-Assignments/pull/3

**Comment by sak55** [comment]
https://github.com/sak55/TIY-Assignments.wiki.git

**Comment by sak55** [comment]
Well times up and I started the final part could not figure out how to incorporate CSS hope to learn in day 3.

**Comment by LoganArnett** [comment]
Looks good Sam, just looking for the next 10 HTML elements and the first 10 CSS elements. The wiki link we're looking for is to [the direct wiki page](https://github.com/sak55/TIY-Assignments/wiki/Growth-and-Fixed-Mindset). Other than that just start building out that blog layout

**Comment by sak55** [comment]
https://github.com/sak55/TIY-Assignments/wiki/Growth-and-Fixed-Mindset
