### ISSUE TITLE
04 -- Surf & Paddle -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#57]
### Tasks

* **Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description ---> S
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!** ---> S
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [x] Checkpoint: First round of feedback!
    * [x] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [x] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle** ---> S
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!** ---> M
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [x] Checkpoint: Pixel perfect page header committed!
    * [x] Checkpoint: Pixel perfect page footer committed!
    * [x] Checkpoint: Pixel perfect column layout committed!
    * [x] Checkpoint: Pixel perfect layout and typography committed!
    * [x] Checkpoint: Links with hover states committed!
    * [x] Mission complete!

**Comment by al-the-x** [comment]
How about a link to that PR, bro?

**Comment by al-the-x** [comment]
You just don't like writing, do you?

**Comment by jrutishauser** [comment]
Hey man. I'm still working @al-the-x

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/5

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#outline

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#rough-draft-so-rough

**Comment by LoganArnett** [comment]
Hey Jon, your Bill and Ted page looks great, just looking for the second draft of the essay and also don't forget to drop a link back to the WIP issue as a comment on your PR's. Other than that start asking your peers for some reviews of that essay and you're good to go

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#rough-draft-number-one--scribbled-fragments

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#rough-draft-so-rough-2

**Comment by al-the-x** [comment]
Still no final draft? No feedback either... I guess you're just an amazing writer. Or you suck at this and should quit writing altogether. Wait, was that a mindset joke?

Seriously, though, you should focus your essay more on a story that serves as an example, particularly something that you're passionate about. Maybe growing hops or brewing beer...? Surely you ran into some difficulty while learning those skills. Analyze and synthesize.
