### ISSUE TITLE
04 -- Surf & Paddle -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#58]
## Requirements

You **MUST** use the following in your implementation:

* [HTML5 Boilerplate](http://html5boilerplate.com), extracted from [this package](http://j.mp/14rYj4L)
* [these fonts from Google Web Fonts](http://www.google.com/fonts#UsePlace:use/Collection:Oswald|Open+Sans) in your implementation -- "Open Sans" for most copy, "Oswald" for headings
* [the FontAwesome icons](http://fortawesome.github.io/Font-Awesome/cheatsheet/) for the "Comments", "Read Later", and "Share This" elements
* an appropriately credited wave or surf icon from [The Noun Project](http://thenounproject.com) for the business logo
* [placeholder text of your choice](http://meettheipsums.com) for all copy (not headings)
* [placeholder images of your choosing](http://lmgtfy.com/?q=placeholder+image+services)

### Tasks

* ** (S) Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* ** (M) To the Final Drafts!**
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* ** (M) Skitch that Paddle**
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf! (L) **
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
    * [ ] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

* **Breakdown of (L) **    
* [x] Make HTML starting point
* [x] break down headings, p's, footer
* [x] changing font style/size
* [x] adding icons
* [ ] editing images

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/5

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by carolinapowers** [comment]
:+1:  good job Josuel! Layout isn't easy. Just a little bit more of time and you'll get it all done. Floating can be complicate... :/

**Comment by LoganArnett** [comment]
You have a lot of great elements in your site and as you have found CSS is a lot of trial and error to just keep moving stuff around. The site looks good just gotta keep tweaking. Make sure you're getting 2 :+1: on all of your PR's before your merge and ask for feedback on your essay drafts. 

Also, when you are creating the files in your repo make sure that you are organizing them in a way that they are easy to find and are well labeled. It was a little difficult to find the files for your site

**Comment by jgarcia99** [comment]
Yea I was going to ask you about my branches. I still have all the feature branches of all my old homework assignments open am i supposed to merge them all to the master branch when I turn them in? @LoganArnett
