### ISSUE TITLE
04 -- Surf & Paddle -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#59]
### Tasks

* **Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!**
    * [ ] Checkpoint: First draft in progress!
    * [ ] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [ ] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle**
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!**
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [x] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by adamkarb** [comment]
[PR](https://github.com/adamkarb/TIY--Assignments/pull/5)

**Comment by LoganArnett** [comment]
Hey Adam, I know your time on the computer was limited this weekend but even so the basic frame you have of the site looks good. The Header is responding well to resizing already, just looks like you need a little bit more time to drop in the other pieces but you're definitely on the right track.

Try to get those drafts written up and reviewed by your peers as well as getting those :+1:  on that PR
