### ISSUE TITLE
04 -- Surf-&-Paddle -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#60]
### Tasks

* **Yak Shaving**...M
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!**...M
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [ ] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle**...M
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!**...XL
    * [x] Checkpoint: HTML5 Boilerplate committed!...M
    * [x] Checkpoint: Basic HTML structure committed!...L
    * [x] Checkpoint: Basic layout CSS committed!...XL
    * [ ] Checkpoint: Pixel perfect page header committed!...L
    * [ ] Checkpoint: Pixel perfect page footer committed!...L
    * [ ] Checkpoint: Pixel perfect column layout committed!...L
    * [ ] Checkpoint: Pixel perfect layout and typography committed!...M
    * [ ] Checkpoint: Links with hover states committed!...M
    * [ ] Mission complete!...XL

**Comment by sak55** [comment]
Link to my pull request :beers: say cheers
https://github.com/sak55/TIY-Assignments/pull/10

**Comment by sak55** [comment]
my wiki - in progress
https://github.com/sak55/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
The drafts of your essay look good, make sure to get some input from your peers on those drafts. The site looks great as well, just gotta keep fiddling with the CSS. Make sure that you are using those read css and html assignments to your advantage and to continue to use them as guides to help you when looking for the right tag or css property
