### ISSUE TITLE
04 -- Surf & Paddle -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#61]
### Tasks

* **Yak Shaving** (M)
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!** (M)
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [x] Checkpoint: First round of feedback!
    * [x] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [x] Checkpoint: More feedback, more revisions!
    * [x] Mission Complete!
* **Skitch that Paddle** (M)
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!** (XL)
    * [x] Checkpoint: HTML5 Boilerplate committed! (S)
    * [x] Checkpoint: Basic HTML structure committed! (L)
    * [x] Checkpoint: Basic layout CSS committed! (L)
    * [x] Checkpoint: Pixel perfect page header committed! (XL)
    * [ ] Checkpoint: Pixel perfect page footer committed! (XL)
    * [x] Checkpoint: Pixel perfect column layout committed! (XL)
    * [ ] Checkpoint: Pixel perfect layout and typography committed! (XL)
    * [ ] Checkpoint: Links with hover states committed! (XL)
    * [ ] Mission complete!

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/4

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by eklemen** [comment]
Essay looks pretty good, I would restate your main talking points briefly in the conclusion

**Comment by mfees** [comment]
:+1: on the essay @carolinapowers!

I really liked how you explained both mindsets, it helped me remember things to add to mine.
My only suggestion is to condense the explanation a little bit and elaborate on the ways you have experienced these mindsets. If I understood correctly (which lets face it who understands anything lol) I think David wanted us to focus on that aspect.

Defining the mindsets in the beginning definitely helps the reader understand. Great job!

(moved to right spot)

**Comment by jgarcia99** [comment]
:+1: on the essay. Could suggest making the conclusion a bit longer.

**Comment by LoganArnett** [comment]
Great job on the Surf and Paddle site and the Essay just make sure that you get one more :+1: on the PR and drop a link back to your WIP issue before you merge it. Outside of that you're good to go

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/4
