### ISSUE TITLE
04 -- Surf & Paddle -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#64]
### Tasks

* ** M Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* ** L To the Final Drafts!**
    * [x] M Checkpoint: First draft in progress!
    * [x] M Checkpoint: First draft complete!
    * [x] S Checkpoint: First round of feedback!
    * [x] S Checkpoint: First revisions!
    * [ ] M Checkpoint: Second draft complete!
    * [ ] S Checkpoint: More feedback, more revisions!
    * [ ] M Mission Complete!
* ** L Skitch that Paddle**
    * [x] S Checkpoint: Loaded the design spec into Skitch!
    * [x] M Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] M Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] M Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] S Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] S Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] M Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* ** XL Now Surf!**
    * [x] S Checkpoint: HTML5 Boilerplate committed!
    * [x] M Checkpoint: Basic HTML structure committed!
    * [x] M Checkpoint: Basic layout CSS committed!
    * [x] M Checkpoint: Pixel perfect page header committed!
    * [ ] M Checkpoint: Pixel perfect page footer committed!
    * [x] M Checkpoint: Pixel perfect column layout committed!
    * [x] M Checkpoint: Pixel perfect layout and typography committed!
    * [x] S Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by jaredstevick** [comment]
First pull request:
https://github.com/jaredstevick/TIY-Assignments/pull/9

**Comment by jaredstevick** [comment]
rough draft... finally
https://github.com/jaredstevick/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
Great job on the Surf and Paddle page, it looks awesome and job on the rough draft, just make sure to ask your peers for revision suggestions and finalize that draft.
