### ISSUE TITLE
05 -- Even More Layout -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#72]
### Tasks

* [ ] **Yak Shaving** -- The Holy Checklist
    [ ] Open a new _WIP Issue_ with **Tasks**
    [ ] Estimate top-level tasks
    [ ] Update your Cloud 9 workspace: `git pull`
    [ ] Create a new branch from `master`
    [ ] Commit the deletion of your previous assignment
    [ ] Push to Github and open a PR
* [ ] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`
* [ ] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/)
  * [ ] Checkpoint: New project clearinghouse :0:
  * [ ] Checkpoint: HTML5 Boilerplate :1:
  * [ ] Checkpoint: Semantic HTML structure :seedling:
  * [ ] Checkpoint: Basic CSS layout :seedling::seedling:
  * [ ] Checkpoint: Icons are for decoration :blossom:
  * [ ] Checkpoint: Time is floating :hourglass:
  * [ ] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_
