### ISSUE TITLE
05 -- Even More Layout -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#74]
### Tasks

* [x] M **Yak Shaving** -- The Holy Checklist :water_buffalo:
    * [x] Open a new _WIP Issue_ with **Tasks** :new:
    * [x] Estimate top-level tasks :hourglass_flowing_sand:
    * [x] Update your Cloud 9 workspace: `git pull` :cloud: 
    * [x] Create a new branch from `master` :evergreen_tree:
    * [x] Commit the deletion of your previous assignment :put_litter_in_its_place:
    * [x] Push to Github and open a PR :wave:
* [x] M **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/` :art:
* [ ] XL [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) :construction:
  * [x] Checkpoint: New project clearinghouse :zero:
  * [x] Checkpoint: HTML5 Boilerplate :one:
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [x] Checkpoint: Icons are for decoration :blossom:
  * [x] Checkpoint: Time is floating :hourglass:
  * [x] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
  * [x] GH Pages Branch :octocat:
  * [x] **BONUS** -- Skitch the _Responsive Breakpoints_ :blowfish:

##BUGS
* [x] Center icons vertically
* [x] Make design responsive
* [x] Change date colors
* [ ] Add carets
* [x] Pick better fonts

**Comment by jaredstevick** [comment]
Pull Request: https://github.com/jaredstevick/TIY-Assignments/pull/10

**Comment by LoganArnett** [comment]
Great job on the timeline, it's a little bit gigantic but it looks good. Just need a little more tinkering with the CSS to mess with those icons.
