### ISSUE TITLE
05 -- Even More Layout -- Adam Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#75]
### Tasks

* [ ] **Yak Shaving** -- The Holy Checklist
 * [x] Open a new _WIP Issue_ with **Tasks** 
 * [x] Estimate top-level tasks
 * [x] Update your Cloud 9 workspace: `git pull`
 * [x] Create a new branch from `master`
 * [x] Commit the deletion of your previous assignment
 * [x] Push to Github and open a PR
* [ ] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`
* [ ] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/)
  * [x] Checkpoint: New project clearinghouse :0:
  * [x] Checkpoint: HTML5 Boilerplate :1:
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [ ] Checkpoint: Icons are for decoration :blossom:
  * [ ] Checkpoint: Time is floating :hourglass:
  * [ ] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by adamkarb** [comment]
[pr](https://github.com/adamkarb/TIY--Assignments/pull/6)

**Comment by al-the-x** [comment]
Closes #72

**Comment by LoganArnett** [comment]
Good job on the layout for the timeline, what happens when you add more `<li>`'s into the mix? 

Make sure to get those :+1: on the PR and then you're good to go

**Comment by al-the-x** [comment]
FYI, you don't need anything other than the link for your PR... Alternately, you can use a reference, e.g. adamkarb/TIY-Assignments#6

**Comment by al-the-x** [comment]
Also just noticed that you have two dashes in your repo name...! :hankey:
