### ISSUE TITLE
05 -- Even More Layout -- Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#76]
### Tasks

* [x] **Yak Shaving** -- The Holy Checklist
    * Open a new _WIP Issue_ with **Tasks**
    * Estimate top-level tasks
    * Update your Cloud 9 workspace: `git pull`
    * Create a new branch from `master`
    * Commit the deletion of your previous assignment
    * Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/)
  * [x] Checkpoint: New project clearinghouse :0:
  * [x] Checkpoint: HTML5 Boilerplate :1:
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [x] Checkpoint: Icons are for decoration :blossom:
  * [x] Checkpoint: Time is floating :hourglass:
  * [x] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/5

**Comment by LoganArnett** [comment]
The timeline looks good man and good job on keeping up with the commits and commit messages
