### ISSUE TITLE
05 -- Even More Layout -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#78]
### Tasks

* [x] **Yak Shaving** -- The Holy Checklist (S)
    * Open a new _WIP Issue_ with **Tasks**
    * Estimate top-level tasks
    * Update your Cloud 9 workspace: `git pull`
    * Create a new branch from `master`
    * Commit the deletion of your previous assignment
    * Push to Github and open a PR
* [ ] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`(M)
* [ ] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) (XL)
  * [x] Checkpoint: New project clearinghouse :zero: (S)
  * [x] Checkpoint: HTML5 Boilerplate :one: (S)
  * [x] Checkpoint: Semantic HTML structure :seedling: (M)
  * [x] Checkpoint: Basic CSS layout :seedling::seedling: (XL)
  * [ ] Checkpoint: Icons are for decoration :blossom: (M)
  * [ ] Checkpoint: Time is floating :hourglass: (M)
  * [ ] Checkpoint: Walk the line :guitar: (L)
  * [ ] Checkpoint: First deployment! :squirrel: (M)
  * [ ] Mission Complete! :checkered_flag: (L)

**Comment by sak55** [comment]
MY PR :baby:

https://github.com/sak55/TIY-Assignments/pull/11

**Comment by sak55** [comment]
### List of bugs and things todo

* [ ] Checkpoint: Icons are for decoration :blossom: (M)
  * [ ] Checkpoint: Time is floating :hourglass: (M)
  * [ ] Checkpoint: Walk the line :guitar: (L)
  * [ ] Checkpoint: First deployment! :squirrel: (M)
  * [ ] Mission Complete! :checkered_flag: (L)
  * [ ] Responsiveness of website when resizing window 
  * [ ] curved box edges
  * [ ] little triangles

**Comment by LoganArnett** [comment]
Looks good Sam, you have a good idea going but look at that CSS and try to figure out why all of the `<article>`'s are sitting on top of each other.
