### ISSUE TITLE
05 -- Even More Layout -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#79]
### Tasks

* [ ] **Yak Shaving** -- The Holy Checklist (L)
    * Open a new _WIP Issue_ with **Tasks** 
    * Estimate top-level tasks
    * Update your Cloud 9 workspace: `git pull`
    * Create a new branch from `master`
    * Commit the deletion of your previous assignment
    * Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/` (M)
* [ ] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) (XL)
  * [x] Checkpoint: New project clearinghouse :zero: 
  * [x] Checkpoint: HTML5 Boilerplate :one: 
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [ ] Checkpoint: Basic CSS layout :seedling::seedling:
  * [ ] Checkpoint: Icons are for decoration :blossom:
  * [ ] Checkpoint: Time is floating :hourglass:
  * [ ] Checkpoint: Walk the line :guitar:
  * [x] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/6

**Comment by carolinapowers** [comment]
https://carolinapowers.github.io/TIY-Assignments

**Comment by carolinapowers** [comment]
Checklist of Bugs:

 * [ ] CSS Layout
 * [ ] Nav Bar to the right lined up with website tittle
 * [ ] Time floated left
 * [ ] Blue vertical line
 * [ ] Time, Icon, Article displayed in line
 * [ ] Make it liquid

**Comment by LoganArnett** [comment]
The timeline looks great Carolina, keep tinkering with the CSS to see what else you can do with the layout you've created
