### ISSUE TITLE
05 -- Even More Layout -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#80]
## Requirements

<strong style="color:red">Note:</strong> You **MUST** have a _WIP Issue_ and _Pull Request (PR)_ that matches the **Deliverables** section above by the due date!

### Tasks

* [x] **Yak Shaving** -- The Holy Checklist (M)
    * Open a new _WIP Issue_ with **Tasks**
    * Estimate top-level tasks
    * Update your Cloud 9 workspace: `git pull`
    * Create a new branch from `master`
    * Commit the deletion of your previous assignment
    * Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`(L)
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) (XL)
  * [x] Checkpoint: New project clearinghouse :0:
  * [x] Checkpoint: HTML5 Boilerplate :1:
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [x] Checkpoint: Icons are for decoration :blossom:
  * [x] Checkpoint: Time is floating :hourglass:
  * [x] Checkpoint: Walk the line :guitar:
  * [x] Checkpoint: First deployment! :squirrel:
  * [x] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/11

**Comment by LoganArnett** [comment]
Good work on the timeline man, make sure when you utilize Boilerplate that you're utilizing the entire template. Other than that you look good to go

**Comment by jgarcia99** [comment]
@LoganArnett so we needed more then the index & html files?
