### ISSUE TITLE
05 -- Even More Layout -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#81]
### Tasks

* [x] **Yak Shaving** -- The Holy Checklist **--> S**
    * [x] Open a new _WIP Issue_ with **Tasks**
    * [x] Estimate top-level tasks
    * [x] Update your Cloud 9 workspace: `git pull`
    * [x] Create a new branch from `master`
    * [x] Commit the deletion of your previous assignment
    * [x] Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/` **-->S**
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) *-->XL*
  * [x] Checkpoint: New project clearinghouse :0: **S**
  * [x] Checkpoint: HTML5 Boilerplate :1: **S**
  * [x] Checkpoint: Semantic HTML structure :seedling: **M**
  * [x] Checkpoint: Basic CSS layout :seedling::seedling: **L**
  * [x] Checkpoint: Icons are for decoration :blossom: **M**
  * [x] Checkpoint: Time is floating :hourglass: **M**
  * [x] Checkpoint: Walk the line :guitar: **XL**
  * [x] Checkpoint: First deployment! :squirrel: **XL**
  * [x] Mission Complete! :checkered_flag: **XXXXXXXXXXXXXL**
* **BONUS** -- Skitch the _Responsive Breakpoints_ **XL, bonus? LOLOLOLOLOLOLOL**

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/6

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/TIY-Assignments/

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/7

**Comment by LoganArnett** [comment]
Looks good Jon, great job on the timeline, just looking for those 2 :+1: on the PR

**Comment by mfees** [comment]
:+1: 
u rock dude

**Comment by eklemen** [comment]
:+1:

**Comment by jrutishauser** [comment]
^ @LoganArnett check out them thumbs
