### ISSUE TITLE
06 -- More Responsive -- Josuel Garcia

### ISSUE THREAD

**Issue by jgarcia99** [TheIronYard--Orlando/FEE--2015--SPRING#85]
## Requirements

**Note:** You **MUST** have a link to your PR in your _WIP Issue_ in order to recieve credit for this assignment!

### Tasks

* [x] **Yak Shaving** (M)
  * Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size** (L)
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size** (L)
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

### Known bugs
**Cant keep the icons to stay on top of the border left when resizing

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/12

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by LoganArnett** [comment]
The timeline looks like its in a good place man, just gotta start messing with those media queries some more. Make sure that you're committing often to be able to keep track of your progress and always look for those :+1: so your peers can review it.

**Comment by jgarcia99** [comment]
jgarcia99/TIY-Assignments#12

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by jgarcia99** [comment]
https://github.com/jgarcia99/TIY-Assignments/pull/14

**Comment by johnalxndr** [comment]
:+1:  good stuff!

**Comment by sak55** [comment]
looks good see if you can get those icons to stick where you want them when resizing the window. :+1:

**Comment by TaylorFoster90** [comment]
:+1:

**Comment by LoganArnett** [comment]
New version is looking good man :white_check_mark:
