### ISSUE TITLE
06 -- More Responsive -- Adam F Karbiener

### ISSUE THREAD

**Issue by adamkarb** [TheIronYard--Orlando/FEE--2015--SPRING#87]
### Tasks

* [x] **Yak Shaving**
  * [x] Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [ ] Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  *  [x] _Immediately_ open a PR!
* [ ] **Vertical Timeline -- Medium Size**
  * [ ] Checkpoint: Skitched it up!
  * [ ] Checkpoint: First medium-size media query!
  * [ ] Checkpoint: Well, I applied some styles...
  * [ ] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size**
  * [ ] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by adamkarb** [comment]
[PR](https://github.com/adamkarb/TIY--Assignments/pull/7)

**Comment by LoganArnett** [comment]
Great job using the media queries to get the timeline responsive. Just looking for the 2 :+1: on that PR, a link back to you WIP on the PR, and a link on this issue to your `index.html` file for the timeline. After that you're good to go :sunglasses:

**Comment by al-the-x** [comment]
Just to be sure, you're aware of why you got **Incomplete** on this assignment?
