### ISSUE TITLE
06 -- More Responsive -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#88]
### Tasks

* [x] **Yak Shaving**
  * Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size** 
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size**
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by sak55** [comment]
my PR can you :eyes: see it???? 
https://github.com/sak55/TIY-Assignments/compare/master...feature/06--more-responsive

**Comment by sak55** [comment]
Link to Index.html
https://github.com/sak55/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by sak55** [comment]
### Known Issues

* [ ]  
* [ ]  
* [ ]  
* [ ]  
* [ ]  
* [ ]

**Comment by LoganArnett** [comment]
The timeline is looking good, just need to start playing with those media queries for the breakpoints. Make sure you are getting the 2 :+1: on the PR's before merging

**Comment by johnalxndr** [comment]
:+1: add those media queries bro!

**Comment by jaredstevick** [comment]
:+1: 1000% more spin!!

**Comment by LoganArnett** [comment]
This version looks awesome man great job :white_check_mark:
