### ISSUE TITLE
06 -- More Responsive -- Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#90]
### Tasks

* [x] **Yak Shaving**
  * Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size**
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size**
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/tree/feature/06--more-responsive

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/6

**Comment by jaredstevick** [comment]
:+1: way to go dude.  you did it!

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/blob/feature/06--more-responsive/pub/initializr/index.html

**Comment by TaylorFoster90** [comment]
known issues :
 *[ ] symbols not on line exactly how they should be
 *[ ] at smallest MQ, time/ date and icons aren't pixel perfect
 *[ ] still cant get the carrot 
 *[ ] when window is at a very small width, the content disappears on the right

**Comment by LoganArnett** [comment]
The timeline looks great man. Just looking for 1 more :+1: on that PR and I cannot seem to find the Small and Medium breakpoint skitches? After that you're good for review. 

The one thing you definitely need to look at though is those commits, you should definitely have more than 3 commits for this assignment. Try even setting a timer like pomodoro and you dont have to take a break if you dont want to but use the timer going off as a way to commit often.

**Comment by jgarcia99** [comment]
:+1:
