### ISSUE TITLE
06 -- More Responsive -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#92]
### Tasks

* [x] **Yak Shaving** **S**
  * [x] Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [x] Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * [x] Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size** **M**
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size** **M**
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/8

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/9

**Comment by LoganArnett** [comment]
The timeline looks great but you have the mobile view for everything? Start messing with those media queries to get the desktop all the way to mobile changes.

**Comment by LoganArnett** [comment]
Thanks for sending me the alternate link for the page it looks great but I would try to incorporate the different media queries into one stylesheet instead of having to load 3 separate files

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/TIY-Assignments/pub/index.html
