### ISSUE TITLE
06 -- More Responsive -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#94]
### Tasks

* [x] **Yak Shaving** (M)
  * Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size**
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size**
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/7

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by carolinapowers** [comment]
Known Issues
[ ] Pixel Perfect the look of CSS Layout
[ ] Apply different colors to <article> and fonts
[ ] Find out how to push skitch into github through command line

**Comment by LoganArnett** [comment]
Great job on the timeline, the responsiveness is excellent. Just need one more peer review :+1: on that PR and you're good to go

**Comment by al-the-x** [comment]
Make sure you start your checklist with either `- [ ]` or `* [ ]` and don't forget the space after. See [_Writing on Github: Task Lists_](https://help.github.com/articles/writing-on-github/#task-lists) for some examples.
