### ISSUE TITLE
08 -- Surf & Paddle, RWD Edition -- Sam Kauffman

### ISSUE THREAD

**Issue by sak55** [TheIronYard--Orlando/FEE--2015--SPRING#99]
### Requirements
**To avoid getting an INCOMPLETE, you MUST have a WIP Issue and PR that matches the Deliverables.**

### Tasks

* [x] **Yak Shaving** (S)
  * [x] Create a new issue with tasks and estimates
  * [x] Create a new branch based on master named 08--surf+paddle+rwd
  * [x] Download, add, and commit the design specs -- full.png and small.png -- to specs/
  * [x] Push and open a Pull Request to master (maybe try using hub pull-request?
  * [x] BONUS: Name your PR something other than the commit message?

* [x] **Skitch!** (M)
  * [x] Checkpoint: Committed full.png and small.png
  * [x] Checkpoint: Annotated full-size header
  * [x] Checkpoint: Annotated small-size header
  * [x] Checkpoint: Annotated full-size article
  * [x] Checkpoint: Annotated small-size article
  * [x] Checkpoint: Annotated full-size footer
  * [x] Checkpoint: Annotated small-size footer
  * [x] Checkpoint: Annotated full-size sidebar
  * [x] Checkpoint: Annotated small-size sidebar

*  [ ] **Surf & Paddle RWD** (XL)
  * [x] Checkpoint: Clean slate
  * [x] Checkpoint: HTML5 Boilerplate
  * [ ] Checkpoint: Adding assets for logo
  * [ ] Checkpoint: Linked fonts for icons and copy
  * [ ] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Small-size footer complete!
  * [ ] Checkpoint: Small-size columns complete!
  * [ ] Checkpoint: Small-size article complete!
  * [ ] Checkpoint: Small-size sidebar complete!
  * [ ] Checkpoint: Small-size layout complete!
  * [ ] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Full-size footer complete!
  * [ ] Checkpoint: Full-size columns complete!
  * [ ] Checkpoint: Full-size article complete!
  * [ ] Checkpoint: Full-size sidebar complete!
  * [ ] Checkpoint: Full-size layout complete!
  * [ ] Checkpoint: Medium-size header complete!
  * [ ] Checkpoint: Medium-size footer complete!
  * [ ] Checkpoint: Medium-size columns complete!
  * [ ] Checkpoint: Medium-size article complete
  * [ ] Checkpoint: Medium-size sidebar complete!
  * [ ] Checkpoint: Medium-size layout complete!

* [ ] **Build a Blog** (L)
  * [x] Checkpoint: Repository exists!
  * [x] Checkpoint: Hello, blog!
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [ ] Checkpoint: Basic MF'g HTML
  * [ ] Checkpoint: Basic 2-column layout
  * [ ] Checkpoint: Header fully styled!
  * [ ] Checkpoint: Footer fully styled!
  * [ ] Checkpoint: Look, ma, I'm a blogger!

* [ ] **Mission Complete!**

**Comment by sak55** [comment]
:eyes:  LOOK ITS ME P-RRRRRRR 
https://github.com/sak55/TIY-Assignments/pull/13

**Comment by sak55** [comment]
To View my index.html in Live Preview
http://htmlpreview.github.io/?https://github.com/sak55/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

**Comment by sak55** [comment]
I HAVE CREATED A BLOG!!!! :fire: 
and here is the link

http://sak55.github.io/

**Comment by LoganArnett** [comment]
Good job Sam, hope you had a great weekend. Make sure to keep up with the checklists for the bug issues/fixes and keep messing with your blog layout

**Comment by al-the-x** [comment]
Love you, bro. Good effort. Weekend trips suck. Until next time, Red Baron.
